// ============================================================================
// TICKET-PMAT-5021: Hook Integration with Gate Executor
// ============================================================================

/// Generate pre-commit hook with quality gate executor (fast mode)
///
/// # TICKET-PMAT-5021
///
/// # Complexity
/// - Time: O(1)
/// - Cyclomatic: 2
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "check_compliance")]
pub fn generate_pre_commit_hook_with_gates_fast() -> String {
    r#"#!/bin/bash
# Pre-commit hook with quality gate executor (fast mode)
# Generated by PMAT ScaffoldEngine - TICKET-PMAT-5021
#
# Fast mode: Runs clippy + tests only (<30s)
# To bypass: git commit --no-verify
# For full gates: Run 'pmat quality-gates' manually

set -e

echo "Running pre-commit quality gates (fast mode)..."

# Check if any source files are staged (skip for docs-only commits)
STAGED_SRC=$(git diff --cached --name-only --diff-filter=ACMR -- '*.rs' '*.py' '*.ts' '*.tsx' '*.js' '*.go' '*.c' '*.cpp' '*.lua' 2>/dev/null || true)
if [ -z "$STAGED_SRC" ]; then
    echo "⏭️  No source files staged (docs-only commit) — skipping quality gates"
    exit 0
fi

# Clippy (strict mode)
echo "→ Running clippy..."
cargo clippy --all-targets --all-features -- -D warnings

# Tests
echo "→ Running tests..."
cargo test --all-features

echo "✓ All quality gates passed!"
echo "ℹ️  For full coverage/complexity checks, run: pmat quality-gates"
exit 0
"#
    .to_string()
}

/// Generate .pmat-gates.toml configuration file
///
/// # TICKET-PMAT-5021
///
/// # Complexity
/// - Time: O(1)
/// - Cyclomatic: 1
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "check_compliance")]
/// The `.pmat-gates.toml` pmat writes for a scaffolded project.
///
/// Every key here is one pmat actually READS. That was not true before: this
/// emitted a `[gates]` table —
///
/// ```toml
/// [gates]
/// run_clippy = true
/// clippy_strict = true
/// run_tests = true
/// test_timeout = 300
/// check_coverage = true
/// min_coverage = 80.0
/// check_complexity = true
/// max_complexity = 10
/// ```
///
/// — and **nothing in pmat parses a `[gates]` section at all**. The readers of
/// this file look for `[entropy]` (`quality_gate_config.rs:173`), `[tdg]`
/// (`check_tdg_grade.rs`) and `[quality]`. So a user ran the scaffolder, got a
/// config file, set `run_tests = false`, and pmat kept running tests — with no
/// error, because an unknown key in TOML is silently ignored.
///
/// That is the shape of #1019 across the fleet: wos has 99 of 99 keys parsed by
/// nothing, whisper.apr 51 of 58 (including a `[file-health]` section where
/// pmat reads `file_health`). A config that is read and satisfied is
/// indistinguishable from one that is never opened — both are silent — so the
/// only defence is to emit nothing that cannot be read.
pub fn generate_gate_config_toml() -> String {
    r#"# PMAT Quality Gate Configuration
# Generated by PMAT ScaffoldEngine
#
# Every key below is read by pmat. Keys pmat does not read are silently
# ignored by TOML, so nothing here is aspirational.

# Entropy gate — read by `quality_gate_config.rs`.
[entropy]
enabled = true
min_pattern_diversity = 0.3
max_violations = 0

# TDG grade gate — read by comply's CB-200 (`check_tdg_grade.rs`).
[tdg]
min_grade = "A"
exclude = []

# Shared thresholds — read by the quality-gate config loader.
[quality]
max_entropy_violations = 0
"#
    .to_string()
}

/// Install quality gate configuration file
///
/// # TICKET-PMAT-5021
///
/// # Complexity
/// - Time: O(1)
/// - Cyclomatic: 2
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "path_exists")]
pub fn install_gate_config(project_dir: &Path) -> Result<()> {
    use std::fs;

    let config_path = project_dir.join(".pmat-gates.toml");
    let toml = generate_gate_config_toml();

    fs::write(&config_path, toml).map_err(ScaffoldError::IoError)?;

    Ok(())
}

/// Install all hooks (pre-commit, post-commit) with quality gates
///
/// # TICKET-PMAT-5021
///
/// # Complexity
/// - Time: O(1)
/// - Cyclomatic: 2
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "path_exists")]
pub fn install_all_hooks_with_gates(project_dir: &Path) -> Result<()> {
    // Install pre-commit hook with gates (fast mode)
    let pre_commit = generate_pre_commit_hook_with_gates_fast();
    install_pre_commit_hook(project_dir, &pre_commit)?;

    // Install post-commit hook (from PMAT-5013)
    install_post_commit_hook(project_dir)?;

    // Install gate configuration
    install_gate_config(project_dir)?;

    Ok(())
}

#[cfg_attr(coverage_nightly, coverage(off))]
#[cfg(test)]
mod generated_config_is_read_tests {
    use super::*;

    /// Every section pmat generates must be one pmat parses.
    ///
    /// #1019: the generator emitted a `[gates]` table with eight keys and
    /// nothing in the codebase parsed a `[gates]` section, so a user who set
    /// `run_tests = false` got no error and no effect. TOML silently ignores
    /// unknown keys, which makes "read and satisfied" indistinguishable from
    /// "never opened".
    ///
    /// This pins the section names against the readers' actual key paths:
    /// `[entropy]` at `quality_gate_config.rs:173`, `[tdg]` in
    /// `check_tdg_grade.rs::load_tdg_gate_overrides`, `[quality]` in the
    /// quality-gate loader.
    #[test]
    fn every_generated_section_has_a_reader() {
        let toml = generate_gate_config_toml();
        let parsed: toml::Table = toml.parse().expect("generated config must be valid TOML");

        let readable = ["entropy", "tdg", "quality"];
        for section in parsed.keys() {
            assert!(
                readable.contains(&section.as_str()),
                "generated a [{section}] section that no pmat reader parses — \
                 the readers handle {readable:?}. A key nothing reads is a \
                 promise the tool does not keep (#1019)."
            );
        }
        assert!(
            !parsed.contains_key("gates"),
            "the dead [gates] table is back"
        );
    }

    /// The generated values must survive the readers that consume them.
    ///
    /// Section names alone are not enough — a `[tdg]` table with the wrong key
    /// spelling is just as dead. whisper.apr shipped a `[file-health]` section
    /// where pmat reads `file_health`, and the hyphen cost it 51 of 58 keys.
    #[test]
    fn generated_keys_match_what_the_readers_ask_for() {
        let parsed: toml::Table = generate_gate_config_toml()
            .parse()
            .expect("valid TOML");

        // `check_tdg_grade.rs::load_tdg_gate_overrides` reads exactly these.
        let tdg = parsed.get("tdg").expect("[tdg] section");
        assert!(tdg.get("min_grade").and_then(|v| v.as_str()).is_some());
        assert!(tdg.get("exclude").and_then(|v| v.as_array()).is_some());

        // `quality_gate_config.rs` reads entropy.min_pattern_diversity.
        let entropy = parsed.get("entropy").expect("[entropy] section");
        assert!(
            entropy
                .get("min_pattern_diversity")
                .and_then(toml::Value::as_float)
                .is_some_and(|v| (0.0..=1.0).contains(&v)),
            "min_pattern_diversity must be a float the reader will not clamp away"
        );
        assert!(entropy.get("enabled").and_then(toml::Value::as_bool).is_some());
    }
}
