// CB-400/401/402: Shell & Makefile quality (bashrs integration)
// Included from quality_checks.rs - shares parent module scope (no `use` imports)

/// Maps a bashrs severity string onto a scored severity.
///
/// Never `Severity::Info`. Info is CB-400's DISCLOSURE channel — rows describing
/// the check's own scope, which by construction do not count against the audited
/// repository (#1049, #1020). Routing an unrecognised bashrs severity there would
/// mean a linter finding pmat could not classify silently stopped counting, which
/// is the exact failure mode the disclosure channel was added to make impossible.
/// Anything not plainly an error is therefore scored as a warning.
fn bashrs_severity(raw: &str) -> Severity {
    match raw {
        "error" => Severity::Error,
        _ => Severity::Warning,
    }
}

/// The only hook names CB-400 has ever looked at. Anything else in
/// `.git/hooks/` — `prepare-commit-msg`, `post-merge`, a `.disabled-*` copy —
/// is invisible to this check, which is precisely why the scope has to be
/// stated rather than left to be inferred from an empty result.
const CB400_HOOK_NAMES: [&str; 4] = ["pre-commit", "pre-push", "commit-msg", "post-commit"];

/// CB-400: Check git hooks with bashrs
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "path_exists")]
pub fn detect_cb400_git_hooks_quality(project_path: &Path) -> Vec<CbPatternViolation> {
    let hooks_dir = project_path.join(".git/hooks");
    if !hooks_dir.exists() {
        return Vec::new();
    }
    let present: Vec<&str> = CB400_HOOK_NAMES
        .into_iter()
        .filter(|name| hooks_dir.join(name).is_file())
        .collect();
    let mut violations: Vec<CbPatternViolation> = present
        .iter()
        .flat_map(|name| lint_single_hook(&hooks_dir, name))
        .collect();
    violations.push(cb400_scope_disclosure(&present));
    violations
}

/// States what CB-400 actually looked at (#1020, acceptance criterion 4).
///
/// Without it, "this repository's hooks are clean", "this repository has no
/// hook by any name CB-400 recognises", and "the hooks here are named something
/// CB-400 never opens" all rendered as the same empty result — an absence
/// reported as a pass. The row is `Info`, so it discloses without accusing.
fn cb400_scope_disclosure(present: &[&str]) -> CbPatternViolation {
    let description = if present.is_empty() {
        format!(
            "scope: none of the {} hook name(s) CB-400 examines ({}) exist here, so no \
             hook was linted. This is not a statement that the repository's hooks are \
             clean.",
            CB400_HOOK_NAMES.len(),
            CB400_HOOK_NAMES.join(", ")
        )
    } else {
        format!(
            "scope: linted {} of {} candidate hook(s) — {}. Hooks under any other name \
             are not examined by CB-400.",
            present.len(),
            CB400_HOOK_NAMES.len(),
            present.join(", ")
        )
    };
    CbPatternViolation {
        pattern_id: "CB-400-SCOPE".to_string(),
        file: ".git/hooks".to_string(),
        line: 0,
        description,
        severity: Severity::Info,
    }
}

/// Does this hook's header say pmat wrote it?
///
/// `.git/hooks/` is per-clone local state that git never tracks, so nothing a
/// repository can commit changes what is in it. When the file there is one pmat
/// itself generated — and marked `DO NOT EDIT` — its shell quality is a property
/// of pmat's generator, not of the audited repository, and CB-400 billing it to
/// that repository produces a finding the only person who sees it cannot act on.
/// See #1049 and #1020.
///
/// The predicate is deliberately narrow: a header comment line that names pmat
/// AND claims authorship, both on the same line. "The hook calls pmat" is not
/// "pmat wrote the hook" — a repository whose own hand-written gate runs
/// `pmat verify` must keep being scored, or the exclusion swallows every
/// pmat-adopting project's real findings.
pub fn hook_is_pmat_generated(content: &str) -> bool {
    const AUTHORSHIP: [&str; 4] = [
        "auto-managed",
        "auto-generated",
        "automatically generated",
        "generated by",
    ];
    content
        .lines()
        .take(15)
        .filter(|line| line.trim_start().starts_with('#'))
        .map(|line| line.to_ascii_lowercase())
        .any(|line| line.contains("pmat") && AUTHORSHIP.iter().any(|m| line.contains(m)))
}

/// The single Info row that stands in for a pmat-generated hook's findings.
///
/// Emitted whether or not there were findings, and whether or not bashrs could
/// run: an unscored file must never be indistinguishable from an absent one.
/// This is the DISCLOSURE half of the exclusion — #1020's fourth acceptance
/// criterion is that an empty result be distinguishable from an unscanned tree.
fn pmat_generated_hook_disclosure(file: String, outcome: &str) -> CbPatternViolation {
    CbPatternViolation {
        pattern_id: "CB-400-PMAT-GENERATED".to_string(),
        file,
        line: 0,
        description: format!(
            "not scored — pmat generated this hook, and git does not track .git/hooks, \
             so no commit in this repository can change it. {outcome} Report those \
             against pmat, not this repo; hooks this repository wrote itself are still \
             scored."
        ),
        severity: Severity::Info,
    }
}

fn lint_single_hook(hooks_dir: &Path, hook_name: &str) -> Vec<CbPatternViolation> {
    let hook_path = hooks_dir.join(hook_name);
    if !hook_path.exists() || hook_path.to_string_lossy().ends_with(".sample") {
        return Vec::new();
    }
    let file = format!(".git/hooks/{hook_name}");
    let pmat_generated = std::fs::read_to_string(&hook_path)
        .map(|content| hook_is_pmat_generated(&content))
        .unwrap_or(false);
    if pmat_generated {
        let outcome = match run_bashrs_lint(&hook_path) {
            Ok(issues) => {
                let errors = issues.iter().filter(|i| i.severity == "error").count();
                let warnings = issues.len() - errors;
                format!("bashrs reports {errors} error(s) and {warnings} warning(s) in it.")
            }
            Err(e) => format!("bashrs could not lint it ({e}), so its own count is unknown."),
        };
        return vec![pmat_generated_hook_disclosure(file, &outcome)];
    }
    match run_bashrs_lint(&hook_path) {
        Ok(issues) => issues
            .into_iter()
            .map(|issue| CbPatternViolation {
                pattern_id: format!("CB-400-{}", issue.code),
                file: file.clone(),
                line: issue.line,
                description: format!("{}: {}", issue.code, issue.message),
                severity: bashrs_severity(&issue.severity),
            })
            .collect(),
        // A hook bashrs could not lint is NOT a hook that passed. This arm used
        // to be `Err(e) if !e.contains("not found")` with an `Err(_) => vec![]`
        // fallthrough, and the spawn-failure message is built two functions
        // below as `format!("bashrs not found: {e}")` — so "bashrs is not
        // installed" was GUARANTEED to match the guard and be discarded as zero
        // violations. On a machine without bashrs, CB-400 reported a clean bill
        // of health for hooks nothing had read. CB-402 was fixed for exactly
        // this in an earlier commit; CB-400 and CB-401 were left behind.
        Err(e) => vec![CbPatternViolation {
            pattern_id: "CB-400-UNMEASURED".to_string(),
            file,
            line: 0,
            description: format!("not measured: {e}"),
            severity: Severity::Warning,
        }],
    }
}

/// CB-401: Check Makefile with bashrs
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "path_exists")]
pub fn detect_cb401_makefile_quality(project_path: &Path) -> Vec<CbPatternViolation> {
    let mut violations = Vec::new();
    let makefile_path = project_path.join("Makefile");

    if !makefile_path.exists() {
        return violations;
    }

    // Run bashrs make lint on Makefile
    match run_bashrs_make_lint(&makefile_path) {
        Ok(issues) if !issues.is_empty() => {
            for issue in issues {
                violations.push(CbPatternViolation {
                    pattern_id: format!("CB-401-{}", issue.code),
                    file: "Makefile".to_string(),
                    line: issue.line,
                    description: format!("{}: {}", issue.code, issue.message),
                    severity: bashrs_severity(&issue.severity),
                });
            }
        }
        Ok(_) => {} // No issues
        // Same fix as CB-400 above: a Makefile bashrs could not lint is not a
        // Makefile that passed, and "not found" was the one error certain to be
        // swallowed.
        Err(e) => {
            violations.push(CbPatternViolation {
                pattern_id: "CB-401-UNMEASURED".to_string(),
                file: "Makefile".to_string(),
                line: 0,
                description: format!("not measured: {e}"),
                severity: Severity::Warning,
            });
        }
    }

    violations
}

/// How many shell scripts CB-402 will lint, and how deep it will look.
///
/// Both are real limits and both are now DISCLOSED when they bite: infra has
/// 104 `.sh` files, 95 of them within depth 4, so a silent `.take(20)` meant
/// the check spoke for 20 files while its message claimed "All shell scripts".
/// Cap on scripts examined per run. 20 was set when the scan was an unbounded
/// directory walk and had to be defended against; scoped to tracked files this
/// repository has 60, so the cap now covers it whole. It stays because a cap
/// that is never reached costs nothing and a scan with no cap is a hazard, and
/// because CB-402-TRUNCATED still reports exactly what a larger repository lost.
const SHELL_SCAN_LIMIT: usize = 250;
const SHELL_SCAN_DEPTH: usize = 4;

/// The shell scripts this repository is answerable for: the ones git tracks.
///
/// Previously an unfiltered `walkdir` at depth 4, excluding only `target/` and
/// `node_modules/`. In this repository that walk finds 160 scripts of which 100
/// are untracked, and `.claude/worktrees/` alone holds 2,780 — ephemeral agent
/// worktrees, each a full copy of the tree, plus vendored third-party installers
/// like `get-docker.sh`. The scan's 20-file budget was consumed entirely by those,
/// so `pmat comply check` reported 40 violations in files the project does not
/// own, while announcing that 140 real scripts went unexamined. Every finding was
/// true of something, and none of it was true of the repository.
///
/// Tracked-ness is the right predicate because it is the project's own answer to
/// "is this our code", maintained by people rather than inferred from a path.
/// Falls back to the directory walk when git cannot answer — a non-repository, or
/// no git binary — because a scan that silently examines nothing would be the
/// failure this check exists to catch.
fn shell_scripts_in_scope(project_path: &Path) -> Vec<std::path::PathBuf> {
    if let Some(tracked) = git_tracked_shell_scripts(project_path) {
        return tracked;
    }
    walk_shell_scripts(project_path)
}

/// Every `.sh` the directory walk can see, tracked or not. Used as the fallback
/// scope outside a git worktree, and as the DISCLOSURE oracle inside one: if git
/// tracks no shell script but the tree contains some, the scan examined nothing
/// and must say so rather than return a clean bill of health.
fn walk_shell_scripts(project_path: &Path) -> Vec<std::path::PathBuf> {
    walkdir::WalkDir::new(project_path)
        .max_depth(SHELL_SCAN_DEPTH)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            let path = e.path();
            path.extension().is_some_and(|ext| ext == "sh")
                && !path.to_string_lossy().contains("target/")
                && !path.to_string_lossy().contains("node_modules/")
        })
        .map(|e| e.path().to_path_buf())
        .collect()
}

/// `git ls-files` restricted to shell scripts, or `None` when git cannot answer.
fn git_tracked_shell_scripts(project_path: &Path) -> Option<Vec<std::path::PathBuf>> {
    let out = std::process::Command::new("git")
        .arg("-C")
        .arg(project_path)
        .args(["ls-files", "-z", "--", "*.sh"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    Some(
        out.stdout
            .split(|b| *b == 0)
            .filter(|s| !s.is_empty())
            .map(|s| project_path.join(String::from_utf8_lossy(s).as_ref()))
            .filter(|p| p.is_file())
            .collect(),
    )
}

/// CB-402: Check shell scripts with bashrs
#[provable_contracts_macros::contract("pmat-core.yaml", equation = "path_exists")]
pub fn detect_cb402_shell_script_quality(project_path: &Path) -> Vec<CbPatternViolation> {
    let mut violations = Vec::new();

    let candidates = shell_scripts_in_scope(project_path);

    // `git ls-files` exits 0 and prints NOTHING in a worktree that tracks no
    // shell script — a fresh `git init` before the first `git add`, a generated
    // or gitignored subdirectory, a sparse checkout. The success-only fallback
    // guard cannot see that case, so the scan would examine zero files, emit no
    // TRUNCATED row, and CB-400 would report Pass. "There are no shell scripts"
    // and "none of the shell scripts here are tracked" are not the same claim.
    if candidates.is_empty() {
        let untracked = walk_shell_scripts(project_path);
        if !untracked.is_empty() {
            violations.push(CbPatternViolation {
                pattern_id: "CB-402-UNTRACKED-ONLY".to_string(),
                file: String::new(),
                line: 0,
                description: format!(
                    "{} shell script(s) exist but git tracks none of them, so none were \
                     examined. Commit them, or run this where they are tracked; a scan \
                     that reached nothing is not a pass.",
                    untracked.len()
                ),
                severity: Severity::Warning,
            });
        }
    }

    let truncated = candidates.len().saturating_sub(SHELL_SCAN_LIMIT);
    let sh_files = candidates.into_iter().take(SHELL_SCAN_LIMIT);

    for entry in sh_files {
        match run_bashrs_lint(&entry) {
            Ok(issues) if !issues.is_empty() => {
                for issue in issues {
                    violations.push(CbPatternViolation {
                        pattern_id: format!("CB-402-{}", issue.code),
                        file: entry
                            .strip_prefix(project_path)
                            .map(|p| p.display().to_string())
                            .unwrap_or_else(|_| entry.display().to_string()),
                        line: issue.line,
                        description: format!("{}: {}", issue.code, issue.message),
                        severity: bashrs_severity(&issue.severity),
                    });
                }
            }
            Ok(_) => {} // No issues
            // A script bashrs could not lint is NOT a script that passed.
            // This was `Err(_) => {}` with the comment "Skip silently for shell
            // scripts", which is how a broken bashrs invocation became a clean
            // bill of health for the whole tree.
            Err(e) => violations.push(CbPatternViolation {
                pattern_id: "CB-402-UNMEASURED".to_string(),
                file: entry
                    .strip_prefix(project_path)
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|_| entry.display().to_string()),
                line: 0,
                description: format!("not measured: {e}"),
                severity: Severity::Warning,
            }),
        }
    }

    // The scan is capped (see `SHELL_SCAN_LIMIT`). Say so, rather than letting
    // 20-of-104 read as 104-of-104.
    if truncated > 0 {
        violations.push(CbPatternViolation {
            pattern_id: "CB-402-TRUNCATED".to_string(),
            file: String::new(),
            line: 0,
            description: format!(
                "{truncated} shell script(s) were NOT examined: the scan stops at \
                 {SHELL_SCAN_LIMIT} files and depth {SHELL_SCAN_DEPTH}. This result \
                 describes the files it reached, not the repository."
            ),
            severity: Severity::Warning,
        });
    }

    violations
}

/// Run bashrs lint on a file and parse results
pub(super) fn run_bashrs_lint(path: &Path) -> Result<Vec<BashrsIssue>, String> {
    use std::process::Command;

    let output = Command::new("bashrs")
        .args(["lint", "--format", "json", "--level", "warning"])
        .arg(path)
        .output()
        .map_err(|e| format!("bashrs not found: {}", e))?;

    if output.status.success() {
        // No issues
        return Ok(Vec::new());
    }

    // Parse JSON output
    let stdout = String::from_utf8_lossy(&output.stdout);
    parse_bashrs_json_output(&stdout)
}

/// Run bashrs make lint on Makefile
pub(super) fn run_bashrs_make_lint(path: &Path) -> Result<Vec<BashrsIssue>, String> {
    use std::process::Command;

    let output = Command::new("bashrs")
        .args(["make", "lint", "--format", "json"])
        .arg(path)
        .output()
        .map_err(|e| format!("bashrs not found: {}", e))?;

    if output.status.success() {
        return Ok(Vec::new());
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    parse_bashrs_json_output(&stdout)
}

/// Parse bashrs JSON output into issues
pub(super) fn parse_bashrs_json_output(json_str: &str) -> Result<Vec<BashrsIssue>, String> {
    // bashrs outputs JSON array of diagnostics
    #[derive(serde::Deserialize)]
    struct BashrsOutput {
        #[serde(default)]
        diagnostics: Vec<BashrsDiagnostic>,
    }

    #[derive(serde::Deserialize)]
    struct BashrsDiagnostic {
        code: String,
        message: String,
        #[serde(default)]
        line: usize,
        #[serde(default)]
        severity: String,
    }

    // Try to parse as array first, then as object. Both read the JSON BODY:
    // bashrs prefixes its stdout with log lines (see `json_body`).
    let json_str = json_body(json_str);
    if let Ok(diagnostics) = serde_json::from_str::<Vec<BashrsDiagnostic>>(json_str) {
        return Ok(diagnostics
            .into_iter()
            .map(|d| BashrsIssue {
                code: d.code,
                message: d.message,
                line: d.line,
                severity: d.severity,
            })
            .collect());
    }

    if let Ok(output) = serde_json::from_str::<BashrsOutput>(json_str) {
        return Ok(output
            .diagnostics
            .into_iter()
            .map(|d| BashrsIssue {
                code: d.code,
                message: d.message,
                line: d.line,
                severity: d.severity,
            })
            .collect());
    }

    // Unparseable output is NOT a clean result.
    //
    // This returned `Ok(Vec::new())` under the comment "graceful degradation",
    // and that one line turned CB-400 into a check that could not fail. bashrs
    // 6.66.2 writes an ANSI-coloured log line to STDOUT before its JSON:
    //
    //     \u{1b}[2m2026-…Z\u{1b}[0m \u{1b}[32m INFO\u{1b}[0m … Linting ./scripts/x.sh
    //     {
    //       "file": "./scripts/x.sh",
    //       "diagnostics": [ … ]
    //
    // so `serde_json` fails on column 1, the empty vec propagates as "no
    // violations", and CB-400 reports `Pass: bashrs: All shell scripts and
    // Makefiles pass quality checks` for a tree where bashrs itself exits 2
    // with 948 errors and 1493 warnings across 59 of 104 scripts.
    //
    // Degrading gracefully is right; degrading SILENTLY into the answer the
    // caller most wants to hear is not. The caller now learns it got nothing.
    Err(format!(
        "bashrs output was not JSON ({} bytes); the first non-log line was: {}",
        json_str.len(),
        json_str
            .lines()
            .find(|l| !l.trim().is_empty())
            .map_or("<empty>", |l| l.trim())
            .chars()
            .take(120)
            .collect::<String>()
    ))
}

/// The JSON body of a bashrs response, with any leading log preamble removed.
///
/// bashrs emits human-readable log lines on stdout ahead of its machine-readable
/// payload, so the payload starts at the first `{` or `[` rather than at byte 0.
/// Skipping to it is what lets the diagnostics actually be read; without this the
/// parse fails and every script looks clean.
fn json_body(raw: &str) -> &str {
    // Anchor on a LINE that opens the payload, not on the first `{`/`[` byte:
    // the log preamble is ANSI-coloured, and every escape sequence contains a
    // literal `[` (`ESC[2m`), so a byte search lands inside the colour code and
    // "fixes" nothing. Found by running it.
    let mut offset = 0usize;
    for line in raw.split_inclusive('\n') {
        if matches!(line.trim_start().as_bytes().first(), Some(b'{' | b'[')) {
            return &raw[offset..];
        }
        offset += line.len();
    }
    raw
}
