[net]
git-fetch-with-cli = true

[build]
incremental = true

[profile.dev.package."*"]
opt-level = 1  # Optimize dependencies even in debug mode

[profile.release]
lto = "thin"
codegen-units = 1

# Ensure deterministic builds
[profile.release.build-override]
codegen-units = 1