version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group tokio ecosystem updates
      tokio-ecosystem:
        patterns:
          - "tokio*"
          - "tower*"
          - "hyper*"
      # Group testing dependencies
      test-dependencies:
        patterns:
          - "tempfile"
          - "criterion"
          - "proptest"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "pragmaticlabs/maintainers"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "pragmaticlabs/maintainers"
    