# Kaizen Test Configuration - Continuous Improvement for Toyota Way Quality
# Zero tolerance for waste (Muda) in test execution

[performance]
# Jidoka - Build quality in from the start
fail_fast = true
max_concurrent_tests = 16  # Optimal for CI systems
timeout_seconds = 30

# Muda elimination - reduce waste
skip_slow_tests_in_ci = true
use_memory_temp_dirs = true
cache_test_data = true

[quality_gates]
# Poka-yoke - Error prevention
max_test_duration_ms = 5000  # Unit tests should be under 5s
max_flaky_test_rate = 0.01   # 1% maximum flaky test rate
min_parallel_efficiency = 0.8  # 80% parallel efficiency target

[kaizen_improvements]
# Continuous improvement tracking
track_performance_metrics = true
generate_improvement_reports = true
auto_optimize_slow_tests = true

[test_categories]
# Different standards for different test types
[test_categories.unit]
max_duration_ms = 100
parallel_execution = true
use_mocks = true

[test_categories.integration]
max_duration_ms = 1000
parallel_execution = true
use_containers = false  # Faster without Docker

[test_categories.e2e]
max_duration_ms = 10000
parallel_execution = false  # E2E tests often conflict
use_real_services = false  # Use mocks for speed

[test_categories.property]
max_duration_ms = 500
test_cases = 20  # Reduced from default 256
shrink_iterations = 100  # Reduced from 1024

[muda_elimination]
# Identify and eliminate waste
track_slow_tests = true
track_flaky_tests = true
track_resource_usage = true
auto_cleanup_temp_files = true

[jidoka_principles]
# Stop and fix problems immediately
fail_on_first_flaky_test = false  # Allow investigation
fail_on_performance_regression = true
fail_on_memory_leaks = true

[genchi_genbutsu]
# Go see the actual problem
detailed_failure_logs = true
capture_system_metrics = true
save_test_artifacts = true