//! The committed record of which tests nothing runs.
//!
//! Counts alone would be a weaker gate than they look. Adding three tests
//! behind `mcp-integration` while deleting three others leaves the count
//! unchanged, and the ledger would call that no change — the exact shape of the
//! defect being gated. The ledger therefore records the FULL MODULE PATH of
//! every unrun test, so a new arrival is named in the diff and an
//! identically-named twin under a different module is a different line.

use super::{reasons, Report};
use std::path::Path;

/// Where the committed ledger lives.
pub const LEDGER_PATH: &str = "docs/status/unrun-tests-ledger.md";

const HEADER: &str = "\
# Unrun tests ledger

Every `#[test]`/`#[tokio::test]` in the **lib** target that no CI leg compiles,
by full module path.

Generated by `pmat analyze unrun-tests --write-ledger`; the same code checks it
with `--check-ledger`, so the generator and the gate cannot disagree. Do not
edit by hand — add a leg that runs the tests, or record a reason in
`src/services/unrun_tests/reasons.rs`.
";

/// Render the ledger for a report.
#[must_use]
pub fn render(report: &Report) -> String {
    let mut s = String::from(HEADER);
    s.push_str(&format!("\nLegs consulted ({}):\n\n", report.legs.len()));
    for leg in &report.legs {
        s.push_str(&format!("- `{leg}`\n"));
    }
    s.push_str(&format!(
        "\n{} of {} lib tests are executed; {} are compiled by no leg.\n",
        report.executed,
        report.total_tests,
        report.unrun.len()
    ));
    for (bucket, members) in report.buckets() {
        s.push_str(&format!(
            "\n## `{bucket}` — {} test(s)\n\n{}\n\n",
            members.len(),
            reasons::reason(&bucket).unwrap_or("NO REASON RECORDED — this ledger is stale")
        ));
        for m in members {
            s.push_str(&m.path);
            s.push('\n');
        }
    }
    s.push_str(&residual(report));
    s
}

/// What the walk could not do, so every count above reads as a floor.
///
/// Recorded IN the ledger rather than printed and forgotten: a new
/// unresolvable `mod` or `include!` hides a whole subtree, and putting it in
/// the diffed artefact is what makes that a reviewed event instead of a
/// silently wider blind spot.
fn residual(report: &Report) -> String {
    let mut s = String::from("\n## Residual — what this walk could not reach\n\n");
    s.push_str(&format!(
        "{} `#[ignore]`d test(s) are compiled by some leg and executed by none.\n\
         `cargo test` prints its own \"N ignored\" line, so they are declared, not\n\
         hidden, and are not ledgered here.\n\n\
         Registered `[[test]]` targets under `tests/` are out of scope: every CI\n\
         invocation is `cargo test --lib`, so enforcing them here would flag 100%\n\
         of that population and say nothing this ledger does not. Files no\n\
         compilation unit reaches at all are `pmat analyze reachability`.\n\n",
        report.ignored
    ));
    if report.unresolved.is_empty() && report.unparsed.is_empty() {
        s.push_str("No unresolved `mod`/`include!` and no unparsable file.\n");
        return s;
    }
    s.push_str(
        "Each line below is a subtree this walk did not enter, so every count above\n\
         is a FLOOR. A new line here hides tests, which is why it lives in the\n\
         diffed artefact rather than in a log.\n\n",
    );
    for u in &report.unresolved {
        s.push_str(&format!("- unresolved: {u}\n"));
    }
    for u in &report.unparsed {
        s.push_str(&format!("- unparsable: {u}\n"));
    }
    s
}

/// What changed between the committed ledger and the tree.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Drift {
    /// Unrun now, absent from the committed ledger. These are the new defects.
    pub added: Vec<String>,
    /// In the committed ledger, no longer unrun (or no longer present).
    pub removed: Vec<String>,
    /// Buckets with no entry in `reasons::REASONS`.
    pub unexplained: Vec<String>,
    /// Reasons recorded for a bucket that no longer exists.
    pub stale_reasons: Vec<String>,
    /// The rendered text differs even though the membership matches.
    pub text_differs: bool,
}

impl Drift {
    #[must_use]
    pub fn is_clean(&self) -> bool {
        self.added.is_empty()
            && self.removed.is_empty()
            && self.unexplained.is_empty()
            && self.stale_reasons.is_empty()
            && !self.text_differs
    }
}

/// Test paths recorded in a ledger's body.
#[must_use]
pub fn paths_in(text: &str) -> Vec<String> {
    let mut v: Vec<String> = text
        .lines()
        .map(str::trim)
        .filter(|l| l.starts_with("crate::"))
        .map(str::to_string)
        .collect();
    v.sort();
    v
}

/// Compare a report against the committed ledger.
#[must_use]
pub fn check(project_root: &Path, report: &Report) -> Drift {
    let rendered = render(report);
    let committed = std::fs::read_to_string(project_root.join(LEDGER_PATH)).unwrap_or_default();
    let old = paths_in(&committed);
    let mut new: Vec<String> = report.unrun.iter().map(|f| f.path.clone()).collect();
    new.sort();

    let buckets: Vec<String> = report.buckets().into_iter().map(|(b, _)| b).collect();
    Drift {
        added: new.iter().filter(|p| !old.contains(p)).cloned().collect(),
        removed: old.iter().filter(|p| !new.contains(p)).cloned().collect(),
        unexplained: buckets
            .iter()
            .filter(|b| reasons::reason(b).is_none())
            .cloned()
            .collect(),
        stale_reasons: reasons::REASONS
            .iter()
            .map(|(b, _)| (*b).to_string())
            .filter(|b| !buckets.contains(b))
            .collect(),
        text_differs: rendered != committed,
    }
}

/// Write the ledger.
///
/// # Errors
///
/// Propagates any filesystem error.
pub fn write(project_root: &Path, report: &Report) -> std::io::Result<()> {
    let path = project_root.join(LEDGER_PATH);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, render(report))
}
