//! The committed record of every tracked `.rs` file no compilation unit reaches.
//!
//! `pmat analyze reachability` has reported 407 orphan files and 82
//! quarantined ones — 8,313 `#[test]` functions no build compiles — since
//! 3.34.0, and nothing in CI, the Makefile or either hook ran it. A count that
//! nobody is required to look at is not a gate (CRUX-12, #1152, #1017).
//!
//! This mirrors `unrun_tests::ledger`: one row per unreachable file, generated
//! and checked by the same code so the two cannot disagree, with a reason
//! drawn from a CLOSED enum every member of which the analyzer can refute.
//! A `pending-#<issue>` row is the bucket the ratchet counts, so it can only
//! shrink; `registered-<target>` and `deleted-<reason>` rows record how a file
//! left that bucket and are checked against git and the walk on every run.

use crate::services::reachability::{Orphan, Report};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// Where the committed ledger lives.
pub const LEDGER_PATH: &str = "docs/status/orphan-files-ledger.md";

/// The tracking issue an orphan is filed under until someone registers it.
const DEFAULT_PENDING_ISSUE: u64 = 1017;
/// The tracking issue for the `pmat_broken_tests` quarantine.
const DEFAULT_QUARANTINE_ISSUE: u64 = 1023;

const HEADER: &str = "\
# Orphan files ledger

Every tracked `.rs` file that no compilation unit reaches — no `mod`, `#[path]`
or `include!` from any target root `cargo metadata` declares — plus the files
reached only through the `pmat_broken_tests` quarantine, which is declared and
never compiled.

Generated by `pmat analyze reachability --write-ledger`; the same code checks it
with `--check-ledger`, so the generator and the gate cannot disagree. The
`reason` column is a CLOSED set, and every value is a claim the checker refutes:

| reason | means | refuted by |
|---|---|---|
| `pending-#<issue>` | still unreachable; tracked on that issue | the file becoming reachable (a stale row) |
| `quarantined-#<issue>` | reached only through `cfg(pmat_broken_tests)` | the analyzer disagreeing |
| `registered-<target>` | was here, now reached from `<target>` | the file still being unreachable |
| `deleted-<reason>` | was here, removed from the tree | the file still being tracked |

The `.pmat-ratchet.toml` metrics `orphan_files` and `quarantined_files` count
the first two buckets and may only fall. To move a file out, register it
(edit the row to `registered-<target>`) or delete it (`deleted-<reason>`) in the
same change; do not edit counts by hand.
";

/// Why a file is in the ledger, or how it left.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Reason {
    /// Still unreachable, tracked on an issue.
    Pending(u64),
    /// Reached only through the quarantine cfg, tracked on an issue.
    Quarantined(u64),
    /// Now reached from the named target.
    Registered(String),
    /// Removed from the tree, for the stated reason.
    Deleted(String),
}

impl Reason {
    /// Parse the closed enum. Anything else is not a reason.
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        if let Some(n) = s.strip_prefix("pending-#") {
            return n.parse().ok().map(Reason::Pending);
        }
        if let Some(n) = s.strip_prefix("quarantined-#") {
            return n.parse().ok().map(Reason::Quarantined);
        }
        // A target or reason that is itself one of the enum's keywords is not
        // a reason: `registered-pending` asserts registration and
        // non-registration in one token, so nothing could check it.
        const KEYWORDS: [&str; 4] = ["pending", "quarantined", "registered", "deleted"];
        if let Some(t) = s.strip_prefix("registered-") {
            return (!t.is_empty() && !KEYWORDS.contains(&t))
                .then(|| Reason::Registered(t.to_string()));
        }
        if let Some(r) = s.strip_prefix("deleted-") {
            return (!r.is_empty() && !KEYWORDS.contains(&r))
                .then(|| Reason::Deleted(r.to_string()));
        }
        None
    }
}

impl std::fmt::Display for Reason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Reason::Pending(n) => write!(f, "pending-#{n}"),
            Reason::Quarantined(n) => write!(f, "quarantined-#{n}"),
            Reason::Registered(t) => write!(f, "registered-{t}"),
            Reason::Deleted(r) => write!(f, "deleted-{r}"),
        }
    }
}

/// One ledger row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Row {
    pub path: String,
    pub reason: Reason,
    pub tests: usize,
    pub lines: usize,
}

/// Rows recorded in a ledger's body. Lines that are not a well-formed row
/// (a reason outside the closed enum, a non-numeric count) are skipped here
/// and reported by [`check`] as `malformed`.
/// The lines of the ledger's row table — everything after the table's
/// `|---|` separator. The header above it carries its own legend table whose
/// cells quote the reason keywords, and that must never be read as rows.
fn body_lines(text: &str) -> impl Iterator<Item = &str> {
    let mut lines = text.lines();
    for l in lines.by_ref() {
        if l.trim() == "|---|---|---|---|" {
            break;
        }
    }
    lines
}

#[must_use]
pub fn rows_in(text: &str) -> Vec<Row> {
    body_lines(text).filter_map(parse_row).collect()
}

fn parse_row(line: &str) -> Option<Row> {
    let line = line.trim();
    if !line.starts_with("| `") {
        return None;
    }
    let cells: Vec<&str> = line.trim_matches('|').split('|').map(str::trim).collect();
    if cells.len() != 4 {
        return None;
    }
    let path = cells[0].trim_matches('`');
    if path.is_empty() {
        return None;
    }
    Some(Row {
        path: path.to_string(),
        reason: Reason::parse(cells[1])?,
        tests: cells[2].parse().ok()?,
        lines: cells[3].parse().ok()?,
    })
}

/// Row lines in a ledger's body that are NOT well-formed — a reason outside
/// the closed enum, or a count that is not a number.
#[must_use]
pub fn malformed_rows_in(text: &str) -> Vec<String> {
    body_lines(text)
        .map(str::trim)
        .filter(|l| l.starts_with("| `") && parse_row(l).is_none())
        .map(str::to_string)
        .collect()
}

/// Every path git tracks under `project_root`.
fn tracked_files(project_root: &Path) -> Option<BTreeSet<String>> {
    let out = std::process::Command::new("git")
        .args(["ls-files", "-z"])
        .current_dir(project_root)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    Some(
        String::from_utf8_lossy(&out.stdout)
            .split('\0')
            .filter(|s| !s.is_empty())
            .map(str::to_string)
            .collect(),
    )
}

/// Render the ledger for a report, carrying forward the committed reasons.
///
/// Every orphan gets a `pending-#` row (the committed issue number if one is
/// recorded, else the default), every quarantined file a `quarantined-#` row.
/// Committed `registered-`/`deleted-` rows are kept only while their claim
/// still verifies — a `registered-` file that is unreachable again, or a
/// `deleted-` file that is tracked again, is dropped from history and shows
/// up as a fresh `pending-#` row, which is what makes a regression visible in
/// the diff.
#[must_use]
pub fn render(project_root: &Path, report: &Report, committed: &[Row]) -> String {
    let tracked = tracked_files(project_root).unwrap_or_default();
    let unreachable: BTreeSet<&str> = report
        .orphans
        .iter()
        .chain(report.quarantined.iter())
        .map(|o| o.path.as_str())
        .collect();
    let by_path: BTreeMap<&str, &Row> = committed.iter().map(|r| (r.path.as_str(), r)).collect();

    let mut rows: Vec<Row> = Vec::new();
    let mut push = |o: &Orphan, default: Reason| {
        let reason = match by_path.get(o.path.as_str()).map(|r| &r.reason) {
            Some(Reason::Pending(n)) if matches!(default, Reason::Pending(_)) => {
                Reason::Pending(*n)
            }
            Some(Reason::Quarantined(n)) if matches!(default, Reason::Quarantined(_)) => {
                Reason::Quarantined(*n)
            }
            _ => default,
        };
        rows.push(Row {
            path: o.path.clone(),
            reason,
            tests: o.tests,
            lines: o.lines,
        });
    };
    for o in &report.orphans {
        push(o, Reason::Pending(DEFAULT_PENDING_ISSUE));
    }
    for o in &report.quarantined {
        push(o, Reason::Quarantined(DEFAULT_QUARANTINE_ISSUE));
    }
    for r in committed {
        let keep = match &r.reason {
            Reason::Registered(_) => {
                tracked.contains(&r.path) && !unreachable.contains(r.path.as_str())
            }
            Reason::Deleted(_) => !tracked.contains(&r.path),
            _ => false,
        };
        if keep {
            rows.push(r.clone());
        }
    }
    rows.sort_by(|a, b| a.path.cmp(&b.path));

    let mut s = String::from(HEADER);
    s.push_str(&format!(
        "\n{} tracked `.rs` files: {} reachable from {} target root(s), {} orphaned \
         ({} lines, {} `#[test]` fns), {} quarantined ({} lines, {} `#[test]` fns).\n",
        report.reachable + report.orphans.len() + report.quarantined.len(),
        report.reachable,
        report.roots,
        report.orphans.len(),
        report.orphan_lines(),
        report.orphan_tests(),
        report.quarantined.len(),
        report.quarantined_lines(),
        report.quarantined_tests(),
    ));
    s.push_str("\n| `path` | reason | tests | lines |\n|---|---|---|---|\n");
    for r in &rows {
        s.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            r.path, r.reason, r.tests, r.lines
        ));
    }
    s.push_str("\n## Residual — what this walk could not reach\n\n");
    if report.unresolved.is_empty() {
        s.push_str("No unresolved `mod` declarations: the counts above are exact.\n");
    } else {
        s.push_str(&format!(
            "{} `mod` declaration(s) name a file this walk could not find, so every count \
             above is a FLOOR. Each is a subtree that may hide more:\n\n",
            report.unresolved.len()
        ));
        // The analyzer reports these with the absolute path it walked from; a
        // committed, byte-compared file must not carry one machine's home dir.
        let root = std::fs::canonicalize(project_root)
            .unwrap_or_else(|_| project_root.to_path_buf())
            .display()
            .to_string();
        for u in &report.unresolved {
            let rel = u
                .strip_prefix(&format!("{root}/"))
                .or_else(|| u.strip_prefix(&root))
                .unwrap_or(u);
            s.push_str(&format!("- unresolved: {rel}\n"));
        }
    }
    s
}

/// What changed between the committed ledger and the tree.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Drift {
    /// Unreachable now, with no row in the committed ledger — new defects.
    pub added: Vec<String>,
    /// A `pending-`/`quarantined-` row whose file is reachable or gone — stale.
    pub removed: Vec<String>,
    /// A row whose reason the tree refutes: `registered-` but still unreachable,
    /// `deleted-` but still tracked, `quarantined-` but not in the quarantine,
    /// `pending-` but not an orphan.
    pub refuted: Vec<String>,
    /// Row lines outside the closed enum or with non-numeric counts.
    pub malformed: Vec<String>,
    /// The rendered text differs even though the membership matches.
    pub text_differs: bool,
}

impl Drift {
    #[must_use]
    pub fn is_clean(&self) -> bool {
        self.added.is_empty()
            && self.removed.is_empty()
            && self.refuted.is_empty()
            && self.malformed.is_empty()
            && !self.text_differs
    }
}

/// Compare a report against the committed ledger.
#[must_use]
pub fn check(project_root: &Path, report: &Report) -> Drift {
    let committed_text =
        std::fs::read_to_string(project_root.join(LEDGER_PATH)).unwrap_or_default();
    let committed = rows_in(&committed_text);
    let tracked = tracked_files(project_root).unwrap_or_default();
    let orphans: BTreeSet<&str> = report.orphans.iter().map(|o| o.path.as_str()).collect();
    let quarantined: BTreeSet<&str> = report.quarantined.iter().map(|o| o.path.as_str()).collect();
    let by_path: BTreeSet<&str> = committed.iter().map(|r| r.path.as_str()).collect();

    let mut drift = Drift {
        malformed: malformed_rows_in(&committed_text),
        ..Drift::default()
    };
    for p in orphans.iter().chain(quarantined.iter()) {
        if !by_path.contains(p) {
            drift.added.push((*p).to_string());
        }
    }
    for r in &committed {
        let p = r.path.as_str();
        match &r.reason {
            Reason::Pending(_) if !orphans.contains(p) => {
                if quarantined.contains(p) {
                    drift
                        .refuted
                        .push(format!("{p}: pending-, but it is quarantined"));
                } else {
                    drift.removed.push(p.to_string());
                }
            }
            Reason::Quarantined(_) if !quarantined.contains(p) => {
                if orphans.contains(p) {
                    drift
                        .refuted
                        .push(format!("{p}: quarantined-, but it is an orphan"));
                } else {
                    drift.removed.push(p.to_string());
                }
            }
            Reason::Registered(_) if !tracked.contains(p) => {
                drift
                    .refuted
                    .push(format!("{p}: registered-, but git does not track it"));
            }
            Reason::Registered(_) if orphans.contains(p) || quarantined.contains(p) => {
                drift
                    .refuted
                    .push(format!("{p}: registered-, but it is still unreachable"));
            }
            Reason::Deleted(_) if tracked.contains(p) => {
                drift
                    .refuted
                    .push(format!("{p}: deleted-, but git still tracks it"));
            }
            _ => {}
        }
    }
    drift.text_differs = render(project_root, report, &committed) != committed_text;
    drift
}

/// Tracked-file changes in `project_root`'s git tree, verbatim (empty when
/// clean). `None` when git is unavailable or this is not a worktree.
fn dirty_tracked_files(project_root: &Path) -> Option<String> {
    let out = std::process::Command::new("git")
        .args(["status", "--porcelain", "--untracked-files=no"])
        .current_dir(project_root)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!s.is_empty()).then_some(s)
}

/// Write the ledger, carrying forward the committed reasons.
///
/// # Errors
///
/// Refuses, without touching the file, when the git tree has uncommitted
/// changes to tracked files and `allow_dirty` is `false` — the generator reads
/// the working tree, and a ledger written over unrelated uncommitted edits
/// records a tree no clean checkout reproduces (the same rule as
/// `unrun_tests::ledger::write`). Propagates filesystem errors.
pub fn write(project_root: &Path, report: &Report, allow_dirty: bool) -> Result<(), String> {
    if !allow_dirty {
        if let Some(dirty) = dirty_tracked_files(project_root) {
            return Err(format!(
                "refusing to write {LEDGER_PATH} from a dirty git tree: it would record \
                 whatever these uncommitted, possibly-unrelated changes happen to add or \
                 remove, not the tree at HEAD. Commit or stash first, or pass --allow-dirty.\n\
                 {dirty}"
            ));
        }
    }
    let path = project_root.join(LEDGER_PATH);
    let committed = std::fs::read_to_string(&path)
        .map(|t| rows_in(&t))
        .unwrap_or_default();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(&path, render(project_root, report, &committed)).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn orphan(path: &str, tests: usize, lines: usize) -> Orphan {
        Orphan {
            path: path.to_string(),
            tests,
            lines,
        }
    }

    #[test]
    fn the_reason_enum_is_closed() {
        assert_eq!(Reason::parse("pending-#1017"), Some(Reason::Pending(1017)));
        assert_eq!(
            Reason::parse("quarantined-#1023"),
            Some(Reason::Quarantined(1023))
        );
        assert_eq!(
            Reason::parse("registered-lib"),
            Some(Reason::Registered("lib".into()))
        );
        assert_eq!(
            Reason::parse("deleted-superseded"),
            Some(Reason::Deleted("superseded".into()))
        );
        for bad in [
            "registered-pending",
            "pending",
            "pending-#x",
            "registered-",
            "known",
            "",
        ] {
            assert_eq!(Reason::parse(bad), None, "{bad:?} must not parse");
        }
        for r in [
            Reason::Pending(7),
            Reason::Quarantined(8),
            Reason::Registered("bin".into()),
            Reason::Deleted("dup".into()),
        ] {
            assert_eq!(Reason::parse(&r.to_string()), Some(r.clone()), "round-trip");
        }
    }

    #[test]
    fn rows_round_trip_through_render() {
        let report = Report {
            reachable: 3,
            orphans: vec![orphan("src/b.rs", 1, 2), orphan("src/a.rs", 0, 5)],
            quarantined: vec![orphan("src/q.rs", 4, 40)],
            roots: 1,
            unresolved: vec![],
        };
        let text = render(Path::new("/nonexistent"), &report, &[]);
        let rows = rows_in(&text);
        assert_eq!(rows.len(), 3);
        assert_eq!(rows[0].path, "src/a.rs", "sorted by path");
        assert_eq!(rows[0].reason, Reason::Pending(DEFAULT_PENDING_ISSUE));
        assert_eq!(
            rows[2].reason,
            Reason::Quarantined(DEFAULT_QUARANTINE_ISSUE)
        );
        assert_eq!((rows[2].tests, rows[2].lines), (4, 40));
        assert!(malformed_rows_in(&text).is_empty());
        assert!(text.contains("2 orphaned (7 lines, 1 `#[test]` fns)"));
    }

    #[test]
    fn committed_pending_issue_numbers_are_carried_forward() {
        let report = Report {
            orphans: vec![orphan("src/a.rs", 0, 1)],
            ..Report::default()
        };
        let committed = vec![Row {
            path: "src/a.rs".into(),
            reason: Reason::Pending(999),
            tests: 0,
            lines: 1,
        }];
        let text = render(Path::new("/nonexistent"), &report, &committed);
        assert!(text.contains("| `src/a.rs` | pending-#999 | 0 | 1 |"));
    }

    #[test]
    fn a_malformed_row_is_reported_not_skipped_silently() {
        let text =
            "|---|---|---|---|\n| `src/a.rs` | registered-pending | 0 | 1 |\n| `src/b.rs` | pending-#1 | x | 1 |\n";
        assert!(rows_in(text).is_empty());
        assert_eq!(malformed_rows_in(text).len(), 2);
    }

    #[test]
    fn check_names_new_stale_and_refuted_rows() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        std::fs::create_dir_all(root.join("docs/status")).expect("mkdir");
        // no git here: tracked_files() is None -> treated as empty
        std::fs::write(
            root.join(LEDGER_PATH),
            "|---|---|---|---|\n| `src/gone.rs` | pending-#1 | 0 | 1 |\n\
             | `src/q.rs` | pending-#1 | 0 | 1 |\n\
             | `src/reg.rs` | registered-lib | 0 | 1 |\n",
        )
        .expect("write");
        let report = Report {
            orphans: vec![orphan("src/new.rs", 1, 1), orphan("src/reg.rs", 1, 1)],
            quarantined: vec![orphan("src/q.rs", 0, 1)],
            ..Report::default()
        };
        let d = check(root, &report);
        assert_eq!(d.added, vec!["src/new.rs".to_string()]);
        assert_eq!(d.removed, vec!["src/gone.rs".to_string()]);
        assert!(d
            .refuted
            .iter()
            .any(|r| r.starts_with("src/q.rs: pending-")));
        assert!(d
            .refuted
            .iter()
            .any(|r| r.starts_with("src/reg.rs: registered-")));
        assert!(!d.is_clean());
    }
}
