//! Hook content generation: templates, environment variables, and quality checks

#![cfg_attr(coverage_nightly, coverage(off))]

use super::hooks_command::HooksCommand;
use crate::services::configuration_service::{configuration, PmatConfig};
use anyhow::Result;
// chrono::Local removed — CB-1335 prohibits timestamps in generated hooks
use std::fs;
use std::path::Path;

impl HooksCommand {
    /// Normalize hook content by removing timestamp line for comparison
    ///
    /// # Complexity
    /// - Time: O(n) where n is content length
    /// - Cyclomatic: 3
    pub(super) fn normalize_hook_content(content: &str) -> String {
        content
            .lines()
            .filter(|line| !line.contains("# Generated at:"))
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Check if a hook is PMAT-managed
    pub(super) fn is_pmat_managed(&self, hook_path: &Path) -> Result<bool> {
        if !hook_path.exists() {
            return Ok(false);
        }

        let content = fs::read_to_string(hook_path)?;
        Ok(content.contains("auto-managed by PMAT") && content.contains("DO NOT EDIT"))
    }

    /// Generate hook content from template and configuration
    /// `strict` is the resolved value (`--strict` OR `[hooks] strict`): the pre-commit
    /// hook and the commit-msg hook must agree, whichever of the two turned it on.
    pub(super) async fn generate_hook_content(&self, strict: bool) -> Result<String> {
        let config_service = configuration();
        let config = config_service.get_config()?;

        let header = self.generate_hook_header();
        let env_vars = self.generate_env_vars(&config, strict || config.hooks.strict);
        let checks = self.generate_quality_checks();

        let hook_content = format!("{header}\n{env_vars}\n{checks}");
        Ok(hook_content)
    }

    /// Generate hook header section
    ///
    /// NOTE: No timestamp — CB-1335 requires deterministic output.
    /// Two consecutive `pmat hooks install` runs must produce identical files.
    #[provable_contracts_macros::contract("pmat-core.yaml", equation = "check_compliance")]
    pub(crate) fn generate_hook_header(&self) -> String {
        r#"#!/bin/bash
# Generated pre-commit hook (auto-managed by PMAT)
# DO NOT EDIT: This file is automatically generated

set -e

echo "🔍 PMAT Pre-commit Quality Gates"
echo "================================"
"#
        .to_string()
    }

    /// Generate environment variables section
    ///
    /// GH-301: `PMAT_PRECOMMIT_EXCLUDE_DIRS` is an escape hatch for directory patterns
    /// that must never be scanned by the hook. Space-separated path prefixes. The
    /// hook defaults cover Claude/Cursor ephemeral worktrees and common build/cache
    /// directories so agent sessions don't balloon pre-commit time.
    fn generate_env_vars(&self, config: &PmatConfig, strict: bool) -> String {
        format!(
            r#"# Load current configuration dynamically
export PMAT_MAX_CYCLOMATIC_COMPLEXITY={}
export PMAT_MAX_COGNITIVE_COMPLEXITY={}
export PMAT_MIN_TEST_COVERAGE={}
export PMAT_MAX_SATD_COMMENTS=5
# AD-03: 1 = SATD over the threshold is REFUSED, not warned about (--strict or [hooks] strict).
# The ticket check lives in the commit-msg hook, which carries [hooks] ticket_pattern itself.
export PMAT_HOOKS_STRICT={}
# GH-301: directories excluded from any hook filesystem scan.
# Override with: PMAT_PRECOMMIT_EXCLUDE_DIRS=".claude/worktrees target ..." git commit
export PMAT_PRECOMMIT_EXCLUDE_DIRS="${{PMAT_PRECOMMIT_EXCLUDE_DIRS:-.claude/worktrees .cursor/worktrees target node_modules .venv}}"
"#,
            config.quality.max_complexity,
            config.quality.max_cognitive_complexity,
            config.quality.min_coverage as u32,
            u8::from(strict)
        )
    }

    /// Generate the cargo fmt --check gate for Rust projects
    fn generate_format_check() -> &'static str {
        r#"# 0. Format check (Rust only — cargo fmt --check on staged .rs files)
STAGED_RS=$(git diff --cached --name-only --diff-filter=ACMR -- '*.rs' 2>/dev/null)
if [ -n "$STAGED_RS" ] && command -v cargo &> /dev/null && [ -f Cargo.toml ]; then
    echo -n "  Format check... "
    # --all matches the pre-push gate. Without it only the current package is
    # checked, so an unformatted file in a workspace MEMBER passes pre-commit
    # and then fails pre-push -- two gates disagreeing about the same repo.
    # `FMT_STATUS=0; ... || FMT_STATUS=$?` rather than testing `$?` after the
    # assignment. The hook runs under `set -e`, and the exit status of
    # `X=$(cmd)` *is* cmd's, so a non-zero rustfmt killed the hook on that line
    # and everything below — the "❌", this message, the diff excerpt — was
    # unreachable. Observed live: "  Format check... " and then exit 1, with no
    # reason printed. A refusal an operator cannot read is a refusal they route
    # around.
    FMT_STATUS=0
    FMT_OUTPUT=$(cargo fmt --all -- --check 2>&1) || FMT_STATUS=$?
    if [ "$FMT_STATUS" -eq 0 ]; then
        echo "✅"
    else
        echo "❌"
        echo "   Unformatted Rust code detected. Run 'cargo fmt' before committing."
        echo "$FMT_OUTPUT" | grep "^Diff in" | head -5
        exit 1
    fi
fi
"#
    }

    /// Generate the clippy gate.
    ///
    /// # The defect this closes
    ///
    /// `049a925a1` committed two clippy errors — `clippy::unnecessary_sort_by`
    /// in `src/services/gate_effect/roster.rs` and `clippy::question_mark` in
    /// `check_evidence_gates.rs` — and the pre-commit hook printed
    /// "✅ All quality gates passed!" on the way out, because it ran format,
    /// complexity and SATD and no lint at all. `ci / lint` runs
    /// `cargo clippy --all-targets -- -D warnings`, so the branch could not have
    /// merged; nothing local said so, and a human reviewer found it three
    /// commits later (`6285aaec6`).
    ///
    /// # Why it is not just `cargo clippy`
    ///
    /// Measured on pmat, warm cache, **no source change at all**:
    /// `cargo clippy --all-targets` 1m06s; `cargo clippy --lib` 3m11s. Narrowing
    /// the target selection is *slower*, not faster — `--lib` and
    /// `--all-targets` resolve features differently and evict each other's
    /// artifacts — so "run clippy only on the files in the commit" is not
    /// available: clippy's unit of work is the crate.
    ///
    /// A minute per commit is the cost that teaches `--no-verify`, which is
    /// worse than no hook. So the gate delegates to `pmat verify --stage clippy`,
    /// which is content-addressed (see [`crate::cli::verify_lint_receipt`]): it
    /// reuses the verdict of the last green clippy run over a byte-identical
    /// tree, and runs clippy for real whenever it cannot. In the loop CLAUDE.md
    /// already mandates — `edit → pmat verify → commit on green` — the gate costs
    /// the fingerprint, ~0.3s. Where it cannot reuse anything it pays full
    /// price, which is the honest answer to not knowing.
    fn generate_clippy_check() -> &'static str {
        r#"
# 2. Clippy gate (Rust only) — see hook_generation.rs for the measurements.
# >>> pmat clippy gate (PMAT-630) >>>
if [ -f Cargo.toml ]; then
    echo -n "  Clippy check... "

    # The gate runs through pmat. If pmat is gone, the gate has not run, and a
    # gate that has not run has not passed. Never `exit 0` from this branch.
    if ! command -v pmat > /dev/null 2>&1; then
        echo "❌"
        echo "   pmat is not in PATH, so the clippy gate could not run."
        echo "   An unchecked gate is not a passed gate."
        echo "   Install with: cargo install pmat"
        echo "   Emergency bypass (leaves a trace): git commit --no-verify"
        exit 1
    fi

    # clippy reads the WORKTREE, never the index. A lint-relevant file that is
    # staged in one state and left in another on disk would be committed
    # without anything having linted the committed bytes. Refuse, rather than
    # imply a coverage this gate does not have.
    STAGED_LINT=$(git diff --cached --name-only --diff-filter=ACMR -- '*.rs' 'Cargo.toml' 'Cargo.lock' 2>/dev/null | sort -u)
    DIRTY_LINT=$(git diff --name-only -- '*.rs' 'Cargo.toml' 'Cargo.lock' 2>/dev/null | sort -u)
    UNSYNCED_LINT=$(printf '%s\n%s\n' "$STAGED_LINT" "$DIRTY_LINT" | sed '/^$/d' | sort | uniq -d)
    if [ -n "$UNSYNCED_LINT" ]; then
        echo "❌"
        echo "   These files are staged in a state that differs from the worktree:"
        # Quoted, then indented by sed. `printf '  %s\n' $VAR` relied on the
        # shell word-splitting the variable, which also splits on spaces -- a
        # path containing one was reported as two nonexistent files (#1020).
        printf '%s\n' "$UNSYNCED_LINT" | sed 's/^/     /'
        echo "   clippy lints the worktree, so the staged bytes would go in unlinted."
        echo "   Stage the rest ('git add <file>') or stash the remainder, then retry."
        exit 1
    fi

    # Content-addressed: ~0.3s when this exact tree already linted green,
    # a full clippy run when it did not. Never a pass without one or the other.
    CLIPPY_STATUS=0
    CLIPPY_OUTPUT=$(pmat verify --stage clippy 2>&1) || CLIPPY_STATUS=$?
    if [ "$CLIPPY_STATUS" -eq 0 ]; then
        echo "✅"
    else
        echo "❌"
        echo "$CLIPPY_OUTPUT" | tail -n 30
        echo ""
        echo "   'ci / lint' runs these same lints; this commit could not merge."
        echo "   Fix: pmat verify --stage clippy --fix"
        exit 1
    fi
fi
# <<< pmat clippy gate (PMAT-630) <<<
"#
    }

    /// Generate quality check sections
    ///
    /// The generated hook is project-type aware:
    /// - Non-code repos (no source files at all) get a fast pass
    /// - Mixed repos only check staged source files
    /// - SATD and docs checks only run when source files exist in the repo
    #[provable_contracts_macros::contract("pmat-core.yaml", equation = "check_compliance")]
    pub(crate) fn generate_quality_checks(&self) -> String {
        let mut hook = String::from(
            r#"# Check if pmat is available.
#
# In a Cargo project this is fatal. Every gate below runs through pmat, the
# clippy gate included, and a hook that cannot run its gates must not report
# that they passed. The previous branch exited zero here with a warning, which
# turned one missing binary into a silent bypass of the entire hook.
if ! command -v pmat &> /dev/null; then
    if [ -f Cargo.toml ]; then
        echo "❌ pmat is not in PATH, and this is a Cargo project."
        echo "   This hook's clippy gate runs through pmat; it cannot be checked"
        echo "   here, and an unchecked gate is not a passed gate."
        echo "   Install with: cargo install pmat"
        echo "   Emergency bypass (leaves a trace): git commit --no-verify"
        exit 1  # fail closed
    fi
    echo "⚠️  Warning: pmat not found in PATH"
    echo "   Install with: cargo install pmat"
    exit 0  # not a Cargo project: nothing here for the clippy gate to check
fi

echo "📊 Running quality gate checks..."

# GH-301: helper that strips PMAT_PRECOMMIT_EXCLUDE_DIRS prefixes from a stream
# of git-tracked paths. Never call `find` here — `find` traverses .gitignore'd
# paths (like .claude/worktrees/*) which blows up pre-commit time on monorepos
# with many agent worktrees and can even invoke nested Makefiles.
_pmat_filter_excluded() {
    if [ -z "$PMAT_PRECOMMIT_EXCLUDE_DIRS" ]; then cat; return; fi
    awk -v excl="$PMAT_PRECOMMIT_EXCLUDE_DIRS" '
        BEGIN { n = split(excl, a, " ") }
        {
            skip = 0
            for (i = 1; i <= n; i++) {
                if (a[i] != "" && index($0, a[i] "/") == 1) { skip = 1; break }
            }
            if (!skip) print
        }
    '
}

# Detect if this repo has any source files at all (not just staged ones).
# Non-code repos (docs, configs, YAML, contracts) get a fast pass.
# Uses `git ls-files` (GH-301) so .gitignore'd directories — including
# .claude/worktrees/, target/, node_modules/ — are never scanned. Outside a
# git worktree we fall back to a bounded find with explicit prunes.
if git rev-parse --git-dir > /dev/null 2>&1; then
    HAS_SOURCE_FILES=$(git ls-files -- \
        '*.rs' '*.py' '*.ts' '*.tsx' '*.js' '*.jsx' \
        '*.go' '*.c' '*.cpp' '*.lua' '*.php' '*.swift' 2>/dev/null \
        | _pmat_filter_excluded | head -n 1)
else
    HAS_SOURCE_FILES=$(find . -maxdepth 4 -type f \( -name '*.rs' -o -name '*.py' -o -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' -o -name '*.go' -o -name '*.c' -o -name '*.cpp' -o -name '*.lua' -o -name '*.php' -o -name '*.swift' \) -not -path './.git/*' -not -path '*/target/*' -not -path '*/node_modules/*' -not -path '*/.claude/worktrees/*' -not -path '*/.cursor/worktrees/*' -print -quit 2>/dev/null)
fi

if [ -z "$HAS_SOURCE_FILES" ]; then
    echo "  Project type: non-code (docs/configs/YAML)"
    echo "  Complexity check... ⏭️  (no source files in repo)"
    echo "  SATD check... ⏭️  (no source files in repo)"
    echo ""
    echo "✅ All quality gates passed!"
    echo ""
    exit 0
fi

"#,
        );
        hook.push_str(Self::generate_format_check());
        hook.push_str(r#"
# 1. Complexity analysis (only staged source files, not entire project)
# Supports: Rust, Python, TypeScript, JavaScript, Go, C, C++, Lua, PHP, Swift
#
# No `head -N` on this list. A cap on the staged-file list is a cap on the
# VERDICT, not on the output: the loop below prints "  Complexity check... OK"
# whether it measured every staged file or only the first twenty, so a commit
# large enough to exceed the cap was reported green over files the gate never
# opened. `git diff --cached --name-only` emits sorted paths, so the SAME
# regions of a tree are the ones dropped every time -- not a random sample.
# If a bound is ever needed for latency it must print the number of files it
# declined to measure and exit non-zero; a silent bound must never print OK.
STAGED_SRC=$(git diff --cached --name-only --diff-filter=ACMR -- '*.rs' '*.py' '*.ts' '*.tsx' '*.js' '*.jsx' '*.go' '*.c' '*.cpp' '*.lua' '*.php' '*.swift' 2>/dev/null)
if [ -n "$STAGED_SRC" ]; then
    echo -n "  Complexity check... "
    COMPLEXITY_FAILED=0
    COMPLEXITY_DETAILS=""
    # `while read` over a here-string, not `for F in $VAR`. Word splitting an
    # unquoted variable also splits on SPACES, so a staged path containing one
    # became two nonexistent paths and its complexity went unchecked (#1020).
    # A here-string rather than a pipe: a pipe would run the body in a subshell
    # and COMPLEXITY_FAILED set inside it would be lost on exit -- the gate
    # would find violations and then pass anyway.
    while IFS= read -r SRC_FILE; do
        if [ -n "$SRC_FILE" ] && [ -f "$SRC_FILE" ]; then
            # ANSI codes MUST be stripped before matching. `pmat analyze
            # complexity` colourises its summary, so the violation line is
            # literally  ESC[1;31mErrors:ESC[0m 2  -- there is no ": " sequence
            # in it, and the previous pattern 'Errors.*: [1-9]' therefore NEVER
            # matched. The gate silently passed every violation: a file
            # measured at Cyclomatic 81 / Cognitive 120 against thresholds of
            # 30/25 committed cleanly. Verified by hand:
            #   raw      ^[[1;31mErrors:^[[0m 2   -> 'Errors.*: [1-9]'  NO MATCH
            #   stripped Errors: 2                -> 'Errors: *[1-9]'   MATCH
            # NO_COLOR is set as well so the sed is belt-and-braces rather than
            # the only line of defence.
            FILE_OUTPUT=$(NO_COLOR=1 pmat analyze complexity --file "$SRC_FILE" --max-cyclomatic $PMAT_MAX_CYCLOMATIC_COMPLEXITY --max-cognitive $PMAT_MAX_COGNITIVE_COMPLEXITY 2>&1 | sed "s/$(printf '\\033')\[[0-9;]*m//g")
            if echo "$FILE_OUTPUT" | grep -qE 'Errors: *[1-9]'; then
                COMPLEXITY_FAILED=1
                # #1033: name the OFFENDER, not just the file.
                # The summary carries one line per violating function:
                #   <name> (<file>:<line>) - Cognitive 27 > 25
                # so grep the "<value> > <limit>" tail. The previous pattern
                # '^[0-9]+\. ' anchored a digit at column 1; pmat indents those
                # lines two spaces, so it matched NOTHING and this block emitted
                # a bare filename followed by a blank line. Worse, had it
                # matched it would have caught the "Top Files by Complexity"
                # aggregate, which the gate does NOT threshold -- thresholds are
                # per FUNCTION (check_function_violations / value > threshold).
                # A file can show an aggregate of 41/44 with every function
                # under 30/25, and a file of 52 trivial functions can aggregate
                # to 73 and fail on one function at 27. Reading the aggregate as
                # the cause produces the wrong repair plan.
                COMPLEXITY_DETAILS="${COMPLEXITY_DETAILS}  ${SRC_FILE}:"$'\n'
                FILE_VIOLATIONS=$(echo "$FILE_OUTPUT" | grep -E '(Cyclomatic|Cognitive) [0-9]+ > [0-9]+' | head -3)
                if [ -n "$FILE_VIOLATIONS" ]; then
                    COMPLEXITY_DETAILS="${COMPLEXITY_DETAILS}${FILE_VIOLATIONS}"$'\n'
                else
                    # Absence must never render as detail. If the summary format
                    # moves, say the offender is unknown -- do not print a bare
                    # filename and let the reader conclude the file is the cause.
                    COMPLEXITY_DETAILS="${COMPLEXITY_DETAILS}    (offender not reported by this pmat build; run: pmat analyze complexity --file ${SRC_FILE})"$'\n'
                fi
            fi
        fi
    done <<< "$STAGED_SRC"
    if [ "$COMPLEXITY_FAILED" -eq 0 ]; then
        echo "✅"
    else
        echo "❌"
        echo "Issues Found:"
        echo "$COMPLEXITY_DETAILS" | head -10
        echo "  Each line above is <function> (<file>:<line>) - <metric> <measured> > <limit>."
        echo "  Limits are PER FUNCTION: Cyclomatic $PMAT_MAX_CYCLOMATIC_COMPLEXITY, Cognitive $PMAT_MAX_COGNITIVE_COMPLEXITY."
        echo "  A file's aggregate in 'Top Files by Complexity' is NOT what this gate tests."
        exit 1
    fi
else
    echo "  Complexity check... ⏭️  (no source files staged)"
fi
"#);
        hook.push_str(Self::generate_clippy_check());
        hook.push_str(r#"
# 3. SATD (Self-Admitted Quality Issues) check - informational only
echo -n "  SATD check... "
# `pmat analyze satd` prints "Total violations:  N". An older pattern looked
# for a phrase pmat never emitted, so the grep matched nothing and the
# `|| echo 0` fallback hardcoded the count to zero. Verified: a file with 3
# SATD markers reported "(0 SATD comments)".
# sed rather than a PCRE grep: PCRE support is GNU-only, and this hook also
# runs on macOS (BSD grep) where it fails and would silently restore the zero.
SATD_OUTPUT=$(pmat analyze satd 2>&1 | sed "s/$(printf '\033')\[[0-9;]*m//g")
SATD_COUNT=$(printf '%s' "$SATD_OUTPUT" | sed -n 's/.*Total violations:[[:space:]]*\([0-9][0-9]*\).*/\1/p' | head -1)
[ -n "$SATD_COUNT" ] || SATD_COUNT=0
if [ "$SATD_COUNT" -le "$PMAT_MAX_SATD_COMMENTS" ] 2>/dev/null; then
    echo "✅ ($SATD_COUNT SATD comments)"
elif [ "${PMAT_HOOKS_STRICT:-0}" = "1" ]; then
    # AD-03: under [hooks] strict this is a refusal. It used to warn and fall
    # through to the success banner (#1126).
    echo "❌ ($SATD_COUNT SATD comments, threshold: $PMAT_MAX_SATD_COMMENTS)"
    echo "   SATD comments exceed the threshold and [hooks] strict is on"
    exit 1
else
    echo "⚠️  ($SATD_COUNT SATD comments, threshold: $PMAT_MAX_SATD_COMMENTS)"
fi

# 4. Documentation synchronization (only if docs structure exists)
if [ -d "docs/execution" ] || [ -f "CHANGELOG.md" ]; then
    echo -n "  Documentation check... "
    if [ -f "docs/execution/roadmap.md" ] && [ -f "CHANGELOG.md" ]; then
        echo "✅"
    else
        echo "⚠️  (docs/execution/roadmap.md or CHANGELOG.md missing)"
    fi
fi

# 5. Task ID validation lives in the commit-msg hook (AD-03): a pre-commit
#    hook receives no message, so the check that used to sit here read an
#    empty "$1" and never ran.

echo ""
echo "✅ All quality gates passed!"
echo ""

# Success
exit 0
"#);
        hook
    }
}

#[cfg(test)]
mod complexity_gate_tests {
    use super::*;
    use std::path::PathBuf;

    /// The generated hook must strip ANSI before matching the violation line.
    ///
    /// Regression for a silent-pass bug: `pmat analyze complexity` colourises
    /// its summary, so the violation line is literally
    /// `ESC[1;31mErrors:ESC[0m 2`. The old pattern `Errors.*: [1-9]` requires a
    /// literal ": " which that byte sequence does not contain, so the gate
    /// matched nothing and passed EVERY violation -- verified live: a file
    /// measuring Cyclomatic 81 / Cognitive 120 against 30/25 thresholds
    /// committed cleanly through the hook.
    #[test]
    fn complexity_gate_strips_ansi_before_matching() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            hook.contains("[0-9;]*m//g"),
            "generated hook must pipe output through sed to strip ANSI codes"
        );
        assert!(
            hook.contains("grep -qE 'Errors: *[1-9]'"),
            "generated hook must use the ANSI-stripped pattern"
        );
        assert!(
            !hook.contains("grep -q 'Errors.*: [1-9]'"),
            "the ANSI-blind pattern must not come back: it never matches \
             colourised output and silently passes all violations"
        );
    }

    /// SATD counting must use the phrase pmat ACTUALLY prints.
    ///
    /// Regression: the hook grepped for "Total SATD comments found: N", which
    /// pmat has never emitted. The real line is "Total violations:  N". The
    /// `|| echo 0` fallback then hardcoded the count to zero, so a file with 3
    /// SATD markers reported "✅ (0 SATD comments)".
    #[test]
    fn satd_gate_matches_the_phrase_pmat_actually_prints() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            !hook.contains("Total SATD comments found:"),
            "pmat never prints this phrase; matching it hardcodes SATD_COUNT to 0"
        );
        assert!(
            hook.contains("Total violations:"),
            "SATD gate must match pmat's real output line"
        );
        assert!(
            !hook.contains("grep -oP"),
            "grep -P is GNU-only; this hook also runs on macOS (BSD grep) where \
             it fails and silently re-introduces a zero count"
        );
    }

    /// The generated hook must not word-split its file lists.
    ///
    /// #1020 asked pmat to stop emitting shell that fails pmat's own linter.
    /// Two of the findings on the shipped hook were genuine, and both were
    /// silent-wrong rather than cosmetic:
    ///
    /// - `for SRC_FILE in $STAGED_SRC` split the staged-file list on SPACES as
    ///   well as newlines, so a staged path containing a space became two paths
    ///   that do not exist, the `[ -f ]` guard skipped both, and the file's
    ///   complexity was never measured. Demonstrated: with `a b.rs` staged, the
    ///   loop body ran zero times and the gate printed a pass.
    /// - `printf '  %s\n' $UNSYNCED_LINT` reported that same path as two
    ///   separate unsynced files.
    ///
    /// The replacement reads with `while IFS= read -r` over a HERE-STRING, not
    /// a pipe: a pipe puts the loop body in a subshell, and `COMPLEXITY_FAILED`
    /// set inside it would be lost on exit -- the gate would find violations
    /// and then pass anyway.
    #[test]
    fn the_generated_hook_does_not_word_split_its_file_lists() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            !hook.contains("for SRC_FILE in $STAGED_SRC"),
            "the unquoted for-loop splits staged paths on spaces and silently \
             skips them"
        );
        assert!(
            hook.contains("while IFS= read -r SRC_FILE"),
            "the staged-file loop must read line by line"
        );
        assert!(
            hook.contains("done <<< \"$STAGED_SRC\""),
            "a here-string, not a pipe: a pipe loses COMPLEXITY_FAILED to a subshell"
        );
        assert!(
            !hook.contains("%s\\n' $UNSYNCED_LINT"),
            "the unsynced-file list must be quoted, not word-split"
        );
    }

    /// A cap on the staged-file list is a cap on the VERDICT.
    ///
    /// The list feeding the complexity gate was built with a trailing
    /// `| head -20`. Nothing downstream knew the list had been truncated, so a
    /// commit staging more than twenty source files was measured over the first
    /// twenty and then printed "  Complexity check... OK" -- a green verdict
    /// over files the gate never opened. Because `git diff --cached
    /// --name-only` emits sorted paths, the files dropped were the same regions
    /// of the tree on every oversized commit, not a random sample.
    ///
    /// The neighbouring audit in #1020 fixed a word-splitting loop four lines
    /// below this cap, which skipped exactly one file with a space in its name,
    /// and did not notice the cap that was skipping arbitrarily many.
    ///
    /// This asserts the absence of ANY `head` on that assignment, not the
    /// absence of the literal `head -20`: a reinstated `head -50` would be the
    /// identical defect with a larger constant.
    #[test]
    fn the_complexity_gate_does_not_cap_the_staged_file_list() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        let assignment = hook
            .lines()
            .find(|l| l.starts_with("STAGED_SRC="))
            .expect("the complexity gate must build a staged-file list");
        assert!(
            !assignment.contains("head"),
            "the staged-file list is capped, so the gate prints a verdict over \
             files it never opened: {assignment}"
        );
    }

    /// Both gates must agree on formatting scope.
    ///
    /// pre-commit used `cargo fmt -- --check` (current package only) while
    /// pre-push uses `cargo fmt --all -- --check`. An unformatted file in a
    /// workspace member therefore passed pre-commit and failed pre-push.
    #[test]
    fn format_gate_uses_workspace_scope() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            hook.contains("cargo fmt --all -- --check"),
            "pre-commit format scope must match pre-push (--all)"
        );
    }

    /// The generated pre-commit hook must run clippy.
    ///
    /// Regression for `049a925a1`, which committed two clippy errors
    /// (`clippy::unnecessary_sort_by` in `src/services/gate_effect/roster.rs`,
    /// `clippy::question_mark` in `check_evidence_gates.rs`) and was told
    /// "✅ All quality gates passed!" on the way out. The hook ran format,
    /// complexity and SATD; `ci / lint` runs
    /// `cargo clippy --all-targets -- -D warnings`, and nothing between the two
    /// did. Only a human reviewer caught it, three commits later (`6285aaec6`).
    #[test]
    fn the_generated_hook_runs_clippy() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            hook.contains("pmat verify --stage clippy"),
            "the pre-commit hook must run the clippy gate; without it a \
             clippy-red tree commits cleanly (049a925a1)"
        );
    }

    /// A gate that can be defeated by not having the tool is not a gate.
    #[test]
    fn a_rust_project_without_pmat_fails_rather_than_passing_quietly() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        // The pmat-missing branch used to `exit 0` unconditionally ("Allow
        // commit but warn"), which silently skipped every gate below it —
        // including the new clippy gate — for anyone whose PATH had drifted.
        assert!(
            hook.contains("exit 1  # fail closed"),
            "a Cargo project whose hook cannot find pmat must fail, not warn"
        );
        assert!(
            !hook.contains("exit 0  # Allow commit but warn"),
            "the unconditional pass-on-missing-pmat branch must not come back"
        );
    }

    /// Clippy lints the worktree, not the index. If a staged file differs from
    /// its worktree copy, the bytes about to be committed are not the bytes
    /// clippy read, and the gate has to say so instead of implying coverage.
    #[test]
    fn the_hook_refuses_when_a_staged_file_differs_from_the_worktree() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            hook.contains("UNSYNCED_LINT"),
            "the hook must detect index/worktree divergence for lint-relevant files"
        );
    }

    /// Asserts the underlying reason directly, independent of the shell:
    /// the raw colourised line contains no literal "Errors: ".
    #[test]
    fn colourised_errors_line_has_no_literal_colon_space() {
        let colourised = "\u{1b}[1;31mErrors:\u{1b}[0m 2";
        assert!(
            !colourised.contains("Errors: "),
            "colourised output has no literal 'Errors: ' -- this is exactly \
             why the old grep never fired"
        );

        // Mirror the sed in the hook, then confirm the shipped pattern matches.
        let mut stripped = String::new();
        let mut chars = colourised.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\u{1b}' {
                for n in chars.by_ref() {
                    if n == 'm' {
                        break;
                    }
                }
            } else {
                stripped.push(c);
            }
        }
        assert_eq!(stripped, "Errors: 2");
    }

    // ---- #1033: the gate must name the OFFENDER ----

    use crate::services::complexity::{
        aggregate_results_with_thresholds, format_complexity_summary, ComplexityMetrics,
        ComplexityReport, FileComplexityMetrics, FunctionComplexity,
    };

    /// Strip ANSI SGR sequences, exactly as the generated hook's `sed` does.
    fn strip_ansi(s: &str) -> String {
        let mut out = String::new();
        let mut chars = s.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\u{1b}' {
                for c2 in chars.by_ref() {
                    if c2 == 'm' {
                        break;
                    }
                }
            } else {
                out.push(c);
            }
        }
        out
    }

    fn func(name: &str, line: u32, cyclomatic: u16, cognitive: u16) -> FunctionComplexity {
        FunctionComplexity {
            name: name.to_string(),
            line_start: line,
            line_end: line + 39,
            metrics: ComplexityMetrics {
                cyclomatic,
                cognitive,
                nesting_max: 3,
                lines: 40,
                halstead: None,
            },
        }
    }

    /// The #1033 scenario, reproduced through the real rules rather than by
    /// hand-building violations.
    ///
    /// `true_peak.rs`: aggregate Cyclomatic 41 / Cognitive 44 — both ABOVE the
    /// 30/25 limits — across functions of which exactly one, `polyphase_peak_4x`
    /// at Cognitive 27, actually violates. The aggregate is a red herring; the
    /// gate thresholds per function.
    fn one_offending_function() -> ComplexityReport {
        let file = FileComplexityMetrics {
            path: "crates/rmedia-core/src/audio_defect/true_peak.rs".to_string(),
            total_complexity: ComplexityMetrics {
                cyclomatic: 41,
                cognitive: 44,
                nesting_max: 4,
                lines: 400,
                halstead: None,
            },
            functions: vec![
                func("polyphase_peak_4x", 146, 12, 27),
                func("reset", 20, 1, 0),
                func("push_sample", 60, 4, 3),
            ],
            classes: vec![],
        };
        aggregate_results_with_thresholds(vec![file], Some(30), Some(25))
    }

    /// The summary names the function, its metric, its MEASURED value and the
    /// limit.
    ///
    /// Before #1033 the whole report was `Errors: 1` — no name, no measurement.
    /// The two numbers a reader did see (30 and 25) were the limits, so the
    /// report contained no measured value at all.
    #[test]
    fn the_summary_names_the_offending_function_and_its_measured_value() {
        let summary = strip_ansi(&format_complexity_summary(&one_offending_function()));
        let found = summary.lines().find(|l| l.contains("polyphase_peak_4x"));
        assert!(
            found.is_some(),
            "no line names the offending function:\n{summary}"
        );
        let offender = found.unwrap_or_default();
        assert!(
            offender.contains("Cognitive 27 > 25"),
            "the offender line must carry the measured value and the limit, got {offender:?}"
        );
        assert!(
            offender.contains("true_peak.rs:146"),
            "the offender line must locate the function, got {offender:?}"
        );
    }

    /// ...and does NOT promote the file aggregate into that list.
    ///
    /// The counter-test. A "fix" that simply printed every complexity number it
    /// could find would satisfy the test above while re-creating the exact
    /// wrong diagnosis #1033 reports: `Top Files by Complexity` shows 41/44
    /// against limits of 30/25, which looks like the cause and is not. Only
    /// functions that actually violate may appear as offenders.
    #[test]
    fn the_summary_does_not_present_the_file_aggregate_as_an_offender() {
        let summary = strip_ansi(&format_complexity_summary(&one_offending_function()));
        let offenders: Vec<&str> = summary
            .lines()
            .filter(|l| offender_regex().is_match(l))
            .collect();
        assert_eq!(
            offenders.len(),
            1,
            "exactly one function violates; got {offenders:?}"
        );
        assert!(
            !offenders[0].contains("41") && !offenders[0].contains("44"),
            "the file aggregate (41/44) must not appear as an offender: {:?}",
            offenders[0]
        );
        for clean in ["reset", "push_sample"] {
            assert!(
                !offenders[0].contains(clean),
                "`{clean}` is under both limits and must not be listed"
            );
        }
    }

    /// The pattern the generated hook greps with, read out of the hook itself.
    ///
    /// Reading it rather than restating it is the point: a test that hard-codes
    /// its own copy of the pattern passes while the shipped hook uses a
    /// different, broken one — which is precisely how `^[0-9]+\. ` survived.
    fn offender_pattern_from_hook(hook: &str) -> String {
        let marker = "grep -E '";
        hook.match_indices(marker)
            .map(|(i, _)| {
                let rest = &hook[i + marker.len()..];
                let end = rest.find('\'').expect("the grep pattern must be closed");
                rest[..end].to_string()
            })
            .find(|p| p.contains("Cyclomatic"))
            .expect("the generated hook must grep for a complexity offender line")
    }

    fn offender_regex() -> regex::Regex {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let pattern = offender_pattern_from_hook(&cmd.generate_quality_checks());
        regex::Regex::new(&pattern).expect("the hook's offender pattern must be a valid regex")
    }

    /// The hook's pattern must match what pmat actually prints.
    ///
    /// This is the coupling the old code got wrong: the hook grepped
    /// `^[0-9]+\. `, anchoring a digit at column 1, while pmat indents those
    /// lines two spaces. It matched nothing, forever, and the hook rendered a
    /// bare filename and a blank line under "Issues Found:". Nothing failed —
    /// absence rendered as detail.
    #[test]
    fn the_hooks_offender_pattern_matches_pmats_real_output() {
        let summary = strip_ansi(&format_complexity_summary(&one_offending_function()));
        let re = offender_regex();
        let matched: Vec<&str> = summary.lines().filter(|l| re.is_match(l)).collect();
        assert!(
            !matched.is_empty(),
            "the hook's pattern {:?} matches nothing in pmat's summary:\n{summary}",
            re.as_str()
        );
        assert!(
            matched.iter().any(|l| l.contains("polyphase_peak_4x")),
            "the hook's pattern matches lines that do not name the offender: {matched:?}"
        );
    }

    /// The dead pattern must not come back, and neither must the message that
    /// printed only the limits.
    #[test]
    fn the_hook_reports_measurements_not_only_limits() {
        let cmd = HooksCommand::new(PathBuf::from("/tmp"), PathBuf::from("/tmp"));
        let hook = cmd.generate_quality_checks();
        assert!(
            !hook.contains(r"grep -E '^[0-9]+\. '"),
            "the column-1-anchored pattern never matched pmat's indented output"
        );
        assert!(
            !hook.contains("Complexity exceeds thresholds (Cyclomatic:"),
            "that line printed the LIMITS with no measurement and no function name; \
             it is the whole of #1033"
        );
        assert!(
            hook.contains("PER FUNCTION"),
            "the hook must say the limits are per function, or the reader goes to \
             the file aggregate and plans the wrong repair"
        );
        assert!(
            hook.contains("offender not reported by this pmat build"),
            "when the pattern matches nothing the hook must say the offender is \
             unknown, not print a bare filename"
        );
    }
}
