graph TD
    src_handlers_tools_AnalyzeDeepContextArgs[AnalyzeDeepContextArgs]
    src_services_deep_context_AstModule[AstModule]
    src_unified_protocol_service_ChurnSummary[ChurnSummary]
    src_demo_adapters_cli_CliApiTrace[CliApiTrace]
    src_services_git_clone_CloneProgress[CloneProgress]
    src_services_code_intelligence_DefectScore[DefectScore]
    src_services_context_FileContext[FileContext]
    src_services_complexity_FunctionComplexity[FunctionComplexity]
    src_services_context_GroupedItems[GroupedItems]
    src_unified_protocol_adapters_http_HttpResponseBuilder[HttpResponseBuilder]
    src_unified_protocol_adapters_http_HttpServer[HttpServer]
    src_demo_export_MarkdownExporter[MarkdownExporter]
    src_unified_protocol_adapters_mcp_McpAdapter[McpAdapter]
    src_models_mcp_McpRequest[McpRequest]
    src_models_mcp_PromptGetParams[PromptGetParams]
    src_services_ast_rust_RustComplexityVisitor[RustComplexityVisitor]
    src_services_unified_ast_engine_UnifiedAstEngine[UnifiedAstEngine]
    src_services_code_intelligence_UnifiedCache[UnifiedCache]
    src_services_deep_context_analyze_churn[analyze_churn]
    src_services_ast_python_analyze_python_file_with_classifier[analyze_python_file_with_classifier]
    src_services_context_build_gitignore[build_gitignore]
    src_cli_mod_calculate_terse_file_risks[calculate_terse_file_risks]
    src_cli_mod_format_full_churn_analysis[format_full_churn_analysis]
    src_cli_mod_format_makefile_sarif[format_makefile_sarif]
    src_cli_mod_format_terse_dead_code_metrics[format_terse_dead_code_metrics]
    src_cli_mod_format_tree_node[format_tree_node]
    src_demo_mod_generate_output[generate_output]
    src_demo_assets_get_asset_hash[get_asset_hash]
    src_services_git_clone[git_clone]
    src_handlers_tools_handle_template_tools[handle_template_tools]
    src_tests_http_adapter_tests[http_adapter_tests]
    src_services_mod[mod]
    src_handlers_tools_parse_tool_call_params[parse_tool_call_params]
    src_demo_mod_print_api_metadata[print_api_metadata]
    src_tests_claude_code_e2e_process_generated_file[process_generated_file]
    src_unified_protocol_adapters_cli_satd_format_to_string[satd_format_to_string]
    src_demo_server_serve_analysis_data[serve_analysis_data]
    src_demo_server_serve_system_diagram[serve_system_diagram]
    src_lib_services[services]
    src_tests_additional_coverage_test_churn_output_format[test_churn_output_format]
    src_tests_demo_comprehensive_tests_test_demo_report_rendering_cli[test_demo_report_rendering_cli]
    src_tests_demo_comprehensive_tests_test_detect_repository_empty_directory[test_detect_repository_empty_directory]
    src_tests_deep_context_tests_test_enum_variants_complete[test_enum_variants_complete]
    src_tests_cli_comprehensive_tests_test_list_command_filters[test_list_command_filters]
    src_tests_unified_protocol_tests_test_service_metrics_creation[test_service_metrics_creation]
    src_tests_unified_protocol_tests_test_service_metrics_duration_tracking[test_service_metrics_duration_tracking]
    src_tests_template_resources_test_template_categories[test_template_categories]
    src_tests_lib_test_template_server_trait_via_methods[test_template_server_trait_via_methods]
    src_unified_protocol_mod_tests[tests]


%% Graph Statistics:
%% Nodes: 1498
%% Edges: 36
