[package]
name = "paiml-mcp-agent-toolkit"
version = "0.1.5"
edition = "2021"
rust-version = "1.80.0"
authors = ["Pragmatic AI Labs"]
description = "MCP server for project scaffolding and template generation"
homepage = "https://paiml.com"
repository = "https://github.com/paiml/paiml-mcp-agent-toolkit"

[dependencies]
# Async runtime
tokio = { version = "1.44", features = ["rt-multi-thread", "macros", "net", "io-util", "io-std", "fs", "sync"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }

# Template engine
handlebars = { version = "6.3", features = ["string_helpers"] }

# Caching
lru = { version = "0.12", features = ["hashbrown"] }

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Logging
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Utilities
sha2 = "0.10"
once_cell = "1.21"
semver = { version = "1.0", features = ["serde"] }
regex = { version = "1.11", features = ["perf"] }
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"

# Async utilities
futures = "0.3"

# CLI support
clap = { version = "4.5", features = ["derive", "env"] }
num_cpus = "1.16"
serde_yaml = "0.9"

# AST parsing
syn = { version = "2.0", features = ["full", "parsing", "visit"] }
proc-macro2 = "1.0"
walkdir = "2.5"
ignore = "0.4"
toml = "0.8"
# For TypeScript/JavaScript parsing
swc_ecma_parser = "0.143"
swc_common = "0.33"
swc_ecma_ast = "0.112"
swc_ecma_visit = "0.98"
# For Python parsing
rustpython-parser = "0.3"

# Installer generation
# installer-macro = { path = "../installer-macro" } # Removed - using simple include_str! instead
blake3 = "1.5"

[dev-dependencies]
mockall = "0.13"
tokio-test = "0.4"
pretty_assertions = "1.4"
tempfile = "3.14"
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = []
# installer-gen = ["installer-macro/installer-gen"] # Removed - no longer needed

[profile.release]
lto = "fat"
codegen-units = 1
# panic = "abort"  # Disabled to prevent terminal crashes during testing
strip = "symbols"
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[[bin]]
name = "paiml-mcp-agent-toolkit"
path = "src/bin/paiml-mcp-agent-toolkit.rs"

# [[bin]]
# name = "generate-installer"
# path = "src/bin/generate-installer.rs"
# required-features = ["installer-gen"]

[[bench]]
name = "critical_path"
harness = false

