# Clippy configuration for paiml-mcp-agent-toolkit

# Allow common patterns that pedantic warns about
allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-print-in-tests = true

# Set thresholds for various metrics
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 8
too-many-lines-threshold = 400
type-complexity-threshold = 250
single-char-binding-names-threshold = 4

# Don't warn about these in tests
avoid-breaking-exported-api = false

# Allow module inception (module with same name as parent)
module-inception = "allow"

# Configure doc requirements
missing-docs-in-crate-items = true