graph TD
    src_handlers_tools_format_churn_as_csv
    src_services_mermaid_property_tests_tests
    src_services_renderer_tests
    src_tests_claude_code_e2e_test_naming_convention_in_individual_templates
    src_tests_tools_test_list_templates_by_toolchain
    src_services_template_service_generate_template
    src_services_cache_strategies
    tests_cli_documentation_sync_test_documentation_examples_are_valid
    src_services_ast_typescript_analyze_typescript_file_with_complexity_cached
    src_services_ast_python_analyze_python_file_with_complexity
    src_services_old_cache_put_metadata
    src_cli_mod_args
    src_services_mod_embedded_templates
    src_utils_helpers
    src_cli_args_validate_params
    src_tests_prompts_create_test_server
    src_tests_resources_test_handle_resource_list
    src_handlers_resources_handle_resource_read
    src_services_mermaid_generator_MermaidGenerator
    src_models_churn_ChurnSummary
    src_services_ast_python_extract_python_items
    src_bin_paiml_mcp_agent_toolkit
    src_services_cache_base_CacheStrategy
    src_handlers_tools_handle_generate_context
    src_handlers_tools_handle_analyze_dag
    src_cli_args_validate_type
    src_tests_tools
    tests_cli_documentation_sync
    src_lib_handlers
    src_services_mod_dag_builder
    src_services_cache_content_cache
    src_tests_cache_test_git_stats_cache
    src_tests_claude_code_e2e_test_claude_code_error_scenarios
    src_models_mcp_McpResponse
    src_services_mermaid_property_tests
    src_services_complexity_format_as_sarif
    src_tests_tools_test_list_templates_by_category
    src_tests_lib_test_warm_cache_templates
    src_handlers_tools_handle_validate_template
    src_services_dag_builder_DagBuilder
    src_tests_template_rendering_test_render_readme_template
    src_cli_mod_matches_include_patterns
    src_cli_mod_handle_analyze_dag
    src_tests_resources_test_handle_resource_read_missing_params
    src_tests_tools_test_search_templates_by_name
    src_tests_template_rendering_test_render_gitignore_template
    src_services_ast_rust
    src_tests_cli_tests_cli_mode_detection_tests
    src_services_mod_template_service
    src_services_complexity_CyclomaticComplexityRule
    src_services_complexity_ComplexitySummary
    src_cli_mod_build_complexity_thresholds
    src_handlers_tools_calculate_relevance
    src_services_complexity_FileComplexityMetrics
    src_tests_template_resources_test_template_parameter_types
    src_services_cache_diagnostics_format_prometheus_metrics
    src_services_ast_typescript
    tests_generate_mermaid_test_generate_test_mermaid
    src_services_git_analysis_CommitInfo
    src_services_ast_python_analyze_python_file
    src_tests_lib_test_template_server_deprecated_methods
    src_tests_cli_tests_cli_error_handling_tests
    src_tests_cli_simple_tests_cli_command_enums
    src_tests_claude_code_e2e_test_ast_context_generation
    src_models_mod_mcp
    tests_mcp_documentation_sync_test_mcp_tool_schemas_match_documentation
    src_tests_lib_test_run_mcp_server_basic
    src_services_mod_mermaid_generator
    src_tests_mcp_protocol_create_request
    src_utils_helpers_to_snake_case
    src_services_ast_python_PythonComplexityVisitor
    src_tests_template_rendering_test_render_deno_typescript_makefile
    src_services_mermaid_generator_MermaidOptions
    src_stateless_server
    src_tests_claude_code_e2e_test_server_info_naming_convention
    tests_mcp_documentation_sync_send_mcp_request
    src_tests_tools_test_scaffold_project_deno
    src_services_template_service_list_all_resources
    src_services_cache_persistent_PersistentCacheEntry
    src_tests_resources_test_handle_resource_read_not_found
    src_tests_e2e_full_coverage_test_cli_generate_validation_error
    src_handlers_tools_AnalyzeCodeChurnArgs
    tests_documentation_examples_get_binary_path
    src_services_complexity_ClassComplexity
    src_handlers_mod
    src_tests_models_test_parameter_type_serialization
    src_handlers_tools_handle_search_templates
    src_services_ast_typescript_analyze_typescript_file_with_complexity
    src_tests_tools_create_test_server
    tests_bin_integration
    src_tests_e2e_full_coverage_test_cli_subcommand_help
    src_models_mcp_PromptGetParams
    src_tests_template_resources
    src_services_complexity_FunctionComplexity
    src_services_cache_strategies_TemplateCacheStrategy
    src_models_mcp_GenerateTemplateArgs
    src_tests_mcp_protocol_test_handle_call_tool_missing_parameters
    src_cli_args_value_type_name
    src_utils_helpers_to_kebab_case
    src_services_cache_strategies_GitStats
    src_services_embedded_templates
    src_tests_tools_test_list_templates_all
    src_services_complexity_ComplexityRule
    src_lib_stateless_server
    src_tests_e2e_full_coverage_test_cli_main_binary_help
    src_services_cache_diagnostics_CacheDiagnostics
    src_handlers_prompts_handle_prompts_list
    src_services_old_cache_put_content
    src_tests_prompts_test_handle_prompt_get_rust_project
    src_models_dag
    src_tests_analyze_cli_tests
    src_services_renderer_TemplateRenderer
    src_tests_mcp_protocol_test_handle_call_tool_invalid_tool
    src_tests_cli_tests
    src_handlers_resources_handle_resource_list
    src_tests_claude_code_e2e_test_claude_code_rust_cli_workflow
    src_tests_claude_code_e2e_test_claude_code_all_languages_scaffold
    src_utils_helpers_current_date_helper
    src_services_context_format_context_as_markdown
    src_tests_cache_test_template_cache
    benches_critical_path
    src_tests_e2e_full_coverage_test_cli_invalid_command
    src_handlers_tools_handle_get_server_info
    src_tests_models_test_toolchain_as_str
    src_tests_error_test_json_error
    tests_generate_mermaid_example
    src_models_mcp_ResourceReadParams
    src_services_ast_rust_analyze_rust_file_with_complexity
    src_services_complexity_compute_complexity_cache_key
    src_tests_template_resources_test_get_template_metadata
    src_tests_lib_test_s3_client_instantiation
    build_main
    src_tests_lib_test_template_server_trait_via_methods
    src_handlers_prompts
    src_tests_resources_test_handle_resource_read_success
    src_lib_TemplateServerTrait
    src_handlers_mod_resources
    src_handlers_tools_handle_generate_template
    src_tests_cli_integration_full_tests
    src_services_cache_diagnostics_CacheEffectiveness
    src_services_cache_diagnostics_CacheStatsSnapshot
    src_tests_ast_e2e_ast_integration_tests
    src_tests_mcp_protocol_test_handle_initialize
    src_models_mod_error
    src_services_renderer_render_template
    src_lib_models
    src_tests_tools_test_validate_template_missing_required
    src_services_git_analysis
    src_tests_template_rendering_test_render_with_string_helpers
    src_services_context_FileContext
    src_services_cache_diagnostics
    src_services_mermaid_generator
    src_utils_helpers_tests
    tests_mcp_documentation_sync_DocumentedTool
    src_tests_error_handling
    src_cli_mod_params_to_json
    src_tests_cache_test_dag_cache
    src_tests_models_test_template_category_serialization
    src_services_ast_typescript_analyze_javascript_file_with_complexity
    tests_documentation_examples_test_jsonc_examples_are_valid
    src_tests_error_test_invalid_uri_error
    src_services_template_service_scaffold_project
    src_tests_additional_coverage_test_additional_model_coverage
    src_services_cache_mod_diagnostics
    src_tests_cli_simple_tests_tests
    src_handlers_tools_handle_list_templates
    src_services_ast_typescript_analyze_typescript_file
    src_tests_cli_tests_cli_integration_tests
    src_services_cache_mod_base
    src_services_git_analysis_GitAnalysisService
    src_services_embedded_templates_list_templates
    src_models_mcp_ScaffoldProjectArgs
    src_tests_e2e_full_coverage_test_cli_analyze_churn
    src_tests_tools_test_search_templates_with_toolchain_filter
    src_models_mod_template
    src_lib_utils
    src_services_template_service_build_template_prefix
    src_services_template_service_extract_filename
    src_services_cache_mod_config
    src_handlers_prompts_handle_prompt_get
    src_services_mod_complexity
    src_services_mod_ast_python
    src_services_mod_cache
    src_tests_lib_test_template_server_trait_implementation
    src_utils_helpers_snake_case_helper
    src_utils_helpers_pascal_case_helper
    src_cli_args_expand_env_vars
    src_services_template_service_ScaffoldError
    src_services_cache_content_cache_ContentCache
    src_services_cache_mod_strategies
    src_tests_template_resources_test_invalid_template_uri
    src_bin_paiml_mcp_agent_toolkit_detect_execution_mode
    src_tests_tools_create_request
    src_services_template_service_validate_parameters
    src_services_complexity_ComplexityVisitor
    src_models_mcp_McpError
    src_models_mod
    src_tests_e2e_full_coverage_test_cli_mode_list_templates
    src_cli_mod_Cli
    src_services_ast_typescript_analyze_javascript_file
    src_cli_args
    tests_generate_mermaid_test
    src_services_context_analyze_rust_file_with_cache
    src_services_context_analyze_project_with_persistent_cache
    src_cli_mod_handle_analyze_churn
    src_services_ast_python
    src_handlers_mod_handle_request
    src_tests_error_test_template_not_found_error
    tests_documentation_examples_test_template_uri_examples_are_valid
    src_models_dag_NodeInfo
    src_tests_error
    src_services_old_cache_get_content
    src_services_renderer
    src_tests_prompts_test_handle_prompt_get_missing_params
    src_tests_tools_test_scaffold_project_rust
    src_models_template_GeneratedTemplate
    src_tests_ast_e2e
    src_services_complexity
    src_tests_lib_test_public_exports
    src_tests_cache_test_churn_cache
    src_services_template_service_list_templates
    src_cli_mod_handle_analyze_complexity
    src_handlers_tools_handle_analyze_code_churn
    src_services_cache_manager
    src_utils_mod
    src_stateless_server_StatelessTemplateServer
    src_services_context_analyze_project
    src_services_dag_builder_filter_import_edges
    src_handlers_tools_GenerateContextArgs
    src_services_embedded_templates_get_template_content
    src_services_cache_base_CacheStats
    src_services_cache_content_cache_CacheMetrics
    tests_cli_documentation_sync_parse_cli_help_output
    src_tests_additional_coverage
    src_tests_error_test_validation_error
    src_services_cache_base
    src_cli_mod_handle_search
    src_tests_resources_create_request
    src_tests_prompts
    src_tests_mcp_protocol_test_handle_call_tool_generate_template
    benches_critical_path_benchmark_template_generation
    tests_mcp_documentation_sync_test_mcp_error_codes_are_complete
    src_tests_lib_test_template_server_new
    src_tests_e2e_full_coverage_test_cli_search_templates
    src_lib_run_mcp_server
    src_handlers_tools_handle_tool_call
    src_tests_template_resources_test_get_template_content
    src_services_ast_rust_analyze_rust_file
    build_verify_dependency_versions
    tests_cli_documentation_sync_test_cli_options_match_documentation
    src_tests_claude_code_e2e_test_naming_convention_critical_requirement
    src_tests_e2e_full_coverage_test_mcp_server_e2e_coverage
    src_tests_template_resources_test_template_categories
    src_tests_mcp_protocol_test_handle_list_tools
    src_tests_cache_test_cache_clear
    src_tests_analyze_cli_tests_tests
    src_services_cache_persistent_PersistentCache
    src_models_churn_CodeChurnAnalysis
    tests_documentation_examples_test_mcp_json_examples_are_valid
    src_services_cache_cache_trait
    src_models_error
    src_services_cache_cache_trait_AstCacheManager
    src_utils_helpers_current_year_helper
    tests_documentation_examples
    src_cli_mod_handle_scaffold
    src_services_context_analyze_rust_file
    src_handlers_tools_AnalyzeDagArgs
    src_tests_template_rendering
    src_tests_claude_code_e2e_create_test_server
    src_handlers_initialize_handle_tools_list
    tests_generate_mermaid_example_generate_example_mermaid_diagram
    src_models_mcp_SearchTemplatesArgs
    src_lib
    src_models_mod_churn
    src_services_mod_ast_typescript
    src_services_embedded_templates_EmbeddedTemplateMetadata
    tests_cli_documentation_sync_test_cli_commands_match_documentation
    src_cli_mod_should_analyze_file
    src_services_git_analysis_FileStats
    src_services_dag_builder
    src_services_context
    src_tests_prompts_test_handle_prompt_get_invalid_params
    src_services_mod_ast_rust
    src_tests_tools_test_validate_template_unknown_parameter
    src_tests_mcp_protocol_create_test_server
    src_models_dag_Edge
    src_services_template_service_validate_template
    src_cli_mod
    src_models_churn_FileChurnMetrics
    src_tests_tools_test_handle_tool_call_invalid_params
    src_tests_error_test_invalid_utf8_error
    src_services_embedded_templates_convert_to_template_resource
    tests_cli_documentation_sync_DocumentedCommand
    src_models_mod_dag
    src_services_template_service_generate_context
    src_tests_e2e_full_coverage_test_cli_main_binary_version
    src_services_template_service_parse_template_uri
    src_tests_prompts_test_handle_prompt_get_unknown_prompt
    src_tests_template_resources_test_rust_template_parameters
    src_tests_lib_test_template_server_cache_initialization
    src_tests_lib_test_template_server_cache_sizes
    src_models_mcp_McpRequest
    src_services_context_ProjectContext
    src_services_complexity_format_complexity_summary
    src_tests_template_rendering_test_render_rust_cli_makefile
    src_tests_lib_test_warm_cache
    src_tests_claude_code_e2e_test_claude_code_search_templates
    src_models_mcp_ValidateTemplateArgs
    src_lib_cli
    src_tests_template_resources_create_test_server
    src_models_mcp
    src_tests_tools_test_handle_tool_call_missing_params
    src_cli_mod_handle_validate
    tests_cli_documentation_sync_test_no_undocumented_commands
    src_tests_helpers
    src_lib_S3Client
    src_services_context_analyze_project_with_cache
    src_services_mod_context
    src_services_cache_strategies_DagCacheStrategy
    src_services_mod_renderer
    src_services_template_service_GeneratedFile
    tests_documentation_examples_test_performance_numbers_are_reasonable
    src_tests_resources_create_test_server
    src_services_cache_mod_manager
    src_tests_claude_code_e2e
    src_tests_template_rendering_test_render_with_nested_loops
    src_tests_mcp_protocol_test_handle_invalid_method
    src_services_complexity_CognitiveComplexityRule
    src_tests_ast_e2e_ast_typescript_tests
    src_services_complexity_ComplexityThresholds
    src_services_cache_config_CacheConfig
    src_tests_lib
    tests_mcp_documentation_sync_parse_documented_mcp_tools
    src_tests_template_resources_test_filter_templates_by_prefix
    src_tests_error_test_render_error
    src_models_template_TemplateResource
    src_services_context_ProjectSummary
    src_tests_prompts_create_request
    src_tests_churn_tests
    src_handlers_tools_AnalyzeComplexityArgs
    tests_mcp_documentation_sync_test_no_undocumented_mcp_tools
    src_cli_mod_handle_generate
    src_models_template
    src_services_complexity_ComplexityMetrics
    src_cli_mod_analyze_file_by_toolchain
    src_services_complexity_ComplexityHotspot
    src_tests_template_rendering_test_render_with_missing_parameters
    src_services_template_service_search_templates
    src_tests_error_handling_error_handling_tests
    src_services_cache_persistent_manager
    src_services_cache_persistent_manager_PersistentCacheManager
    src_services_template_service_ValidationResult
    src_tests_template_rendering_test_render_python_uv_makefile
    tests_documentation_examples_test_yaml_examples_are_valid
    src_tests_template_rendering_test_render_with_conditionals
    src_lib_tests
    src_tests_resources_test_handle_resource_read_all_templates
    src_tests_e2e_full_coverage
    src_models_churn
    tests_bin_integration_test_binary_invalid_json
    tests_mcp_documentation_sync_get_binary_path
    src_tests_error_test_cache_error
    src_models_template_ParameterSpec
    src_services_old_cache
    build
    src_tests_mcp_protocol
    src_tests_additional_coverage_test_churn_output_format
    src_utils_helpers_kebab_case_helper
    src_tests_models
    src_handlers_initialize
    src_services_cache_mod_cache_trait
    src_models_mcp_Prompt
    src_tests_error_test_io_error
    tests_bin_integration_test_binary_json_rpc_initialize
    src_services_context_analyze_rust_file_with_persistent_cache
    src_tests_error_test_s3_error
    src_tests_cli_tests_cli_args_tests
    tests_bin_integration_test_binary_version_flag
    src_tests_lib_test_type_aliases
    src_cli_mod_handle_list
    src_services_mod_git_analysis
    src_tests_resources
    src_handlers_mod_tools
    src_services_dag_builder_filter_call_edges
    src_handlers_tools
    tests_cli_documentation_sync_get_binary_path
    src_tests_tools_test_validate_template_not_found
    src_services_template_service_ValidationError
    src_tests_cli_simple_tests
    src_cli_mod_print_table
    tests_bin_integration_test_binary_multiple_requests
    src_tests_additional_coverage_test_cli_validate_params
    src_handlers_tools_format_churn_summary
    src_services_cache_manager_SessionCacheManager
    tests_cli_documentation_sync_test_cli_subcommands_match_documentation
    src_tests_cli_tests_cli_parsing_tests
    src_services_cache_mod_persistent_manager
    src_lib_TemplateServer
    src_models_mcp_ListTemplatesArgs
    src_services_template_service_ScaffoldResult
    src_services_template_service_get_template_content
    src_cli_mod_analyze_project_files
    src_tests_cli_tests_cli_output_tests
    src_handlers_tools_handle_analyze_complexity
    src_services_template_service
    src_cli_mod_run
    src_tests_mcp_protocol_test_handle_list_resources
    src_bin_paiml_mcp_agent_toolkit_main
    src_utils_helpers_to_pascal_case
    src_handlers_mod_initialize
    src_handlers_mod_prompts
    src_services_cache_config
    src_handlers_tools_handle_scaffold_project
    tests_mcp_documentation_sync_test_mcp_tools_match_documentation
    src_handlers_tools_format_churn_as_markdown
    tests_mcp_documentation_sync
    src_tests_error_test_not_found_error
    src_tests_cache
    src_services_old_cache_get_metadata
    src_services_embedded_templates_EmbeddedParameter
    src_services_cache_strategies_ChurnCacheStrategy
    src_tests_resources_test_handle_resource_read_invalid_params
    tests_cli_documentation_sync_parse_documented_cli_commands
    tests_mcp_documentation_sync_McpResponse
    src_tests_cache_test_ast_cache
    src_tests_churn
    src_services_cache_strategies_GitStatsCacheStrategy
    src_tests_ast_e2e_ast_python_tests
    src_services_cache_mod_content_cache
    src_models_dag_DependencyGraph
    tests_mcp_documentation_sync_test_mcp_methods_match_documentation
    src_services_mermaid_generator_property_tests
    src_services_complexity_aggregate_results
    src_services_cache_base_CacheEntry
    src_tests_cli_integration_full
    src_tests_prompts_test_handle_prompts_list
    src_tests_prompts_test_handle_prompt_get_python_project
    src_tests_claude_code_e2e_create_tool_request
    src_utils_mod_helpers
    src_tests_template_resources_test_list_all_templates
    src_handlers_initialize_handle_initialize
    src_tests_template_resources_test_template_toolchains
    src_tests_tools_test_validate_template_valid
    src_handlers_resources
    src_tests_tools_test_generate_template_invalid_arguments
    src_tests_cache_test_cache_ttl
    src_tests_build_naming_validation_tests
    src_tests_mcp_protocol_test_protocol_version_default
    tests_mcp_documentation_sync_ToolDefinition
    tests_documentation_examples_test_cli_examples_are_valid
    src_services_cache_strategies_AstCacheStrategy
    src_services_complexity_format_complexity_report
    src_tests_prompts_test_handle_prompt_get_deno_project
    src_cli_mod_parse_key_val
    src_services_cache_diagnostics_CacheDiagnosticReport
    src_lib_services
    src_services_ast_typescript_TypeScriptVisitor
    src_services_cache_mod_persistent
    src_services_ast_rust_RustComplexityVisitor
    src_models_mcp_PromptArgument
    src_services_complexity_ComplexityReport
    src_services_template_service_SearchResult
    src_services_cache_mod
    src_services_context_RustVisitor
    src_tests_cache_test_session_cache_manager
    src_tests_tools_test_search_templates_no_results
    src_cli_mod_detect_toolchain
    src_services_mermaid_generator_tests
    src_tests_helpers_helpers_tests
    src_tests_models_test_toolchain_priority
    src_models_mcp_ToolCallParams
    src_services_dag_builder_filter_inheritance_edges
    src_services_mod
    src_cli_mod_handle_context
    src_tests_cache_test_cache_eviction
    src_services_embedded_templates_get_template_metadata
    src_tests_build_naming_validation
    src_services_cache_persistent

    src_lib_TemplateServer -->|inherits| src_lib_TemplateServerTrait
    src_stateless_server_StatelessTemplateServer -->|inherits| src_lib_TemplateServerTrait
    src_services_complexity_CyclomaticComplexityRule -->|inherits| src_services_complexity_ComplexityRule
    src_services_complexity_CognitiveComplexityRule -->|inherits| src_services_complexity_ComplexityRule
    src_services_cache_strategies_AstCacheStrategy -->|inherits| src_services_cache_base_CacheStrategy
    src_services_cache_strategies_TemplateCacheStrategy -->|inherits| src_services_cache_base_CacheStrategy
    src_services_cache_strategies_DagCacheStrategy -->|inherits| src_services_cache_base_CacheStrategy
    src_services_cache_strategies_ChurnCacheStrategy -->|inherits| src_services_cache_base_CacheStrategy
    src_services_cache_strategies_GitStatsCacheStrategy -->|inherits| src_services_cache_base_CacheStrategy

%% Graph Statistics:
%% Nodes: 478
%% Edges: 300
