graph TD
    src_unified_protocol_service_AnalysisService((AnalysisService))
    src_services_cache_content_cache_CacheMetrics[CacheMetrics]
    src_services_deep_context_CategorizedAstItems[CategorizedAstItems]
    src_unified_protocol_service_ChurnAnalysis[ChurnAnalysis]
    src_services_ranking_ChurnScore[ChurnScore]
    src_demo_adapters_cli_CliApiTrace[CliApiTrace]
    src_services_complexity_ComplexitySummary[ComplexitySummary]
    src_demo_config_ConfigManager[ConfigManager]
    src_services_dead_code_analyzer_CoverageData[CoverageData]
    src_services_file_classifier_DebugReport[DebugReport]
    src_demo_adapters_mcp_DemoAnalyzeParams[DemoAnalyzeParams]
    src_demo_adapters_mcp_DemoGetApiTraceParams[DemoGetApiTraceParams]
    src_services_deep_context_DriftAnalysis[DriftAnalysis]
    src_cli_mod_EarlyCliArgs[EarlyCliArgs]
    src_services_deep_context_FileChurnMetrics[FileChurnMetrics]
    src_services_file_classifier_FileClassifier[FileClassifier]
    src_services_git_clone_GitCloner[GitCloner]
    src_services_ast_strategies_JavaScriptAstStrategy[JavaScriptAstStrategy]
    src_unified_protocol_adapters_mcp_JsonRpcError[JsonRpcError]
    src_services_makefile_linter_ast_MakefileNode[MakefileNode]
    src_services_context_ProjectSummary[ProjectSummary]
    src_models_tdg_TDGSummary[TDGSummary]
    src_unified_protocol_mod_UnifiedResponse[UnifiedResponse]
    src_services_duplicate_detector_VectorizedLSH[VectorizedLSH]
    src_services_mod_ast_typescript[ast_typescript]
    src_cli_mod_calculate_terse_median_changes[calculate_terse_median_changes]
    src_handlers_tools_dispatch_tool_call[dispatch_tool_call]
    src_models_error[error]
    src_cli_mod_format_full_churn_analysis[format_full_churn_analysis]
    src_cli_mod_format_makefile_gcc[format_makefile_gcc]
    src_cli_mod_format_terse_complexity_metrics[format_terse_complexity_metrics]
    src_services_template_service_get_template_content[get_template_content]
    src_handlers_tools_handle_analysis_tools[handle_analysis_tools]
    src_cli_mod_handle_analyze_complexity[handle_analyze_complexity]
    src_cli_mod_handle_analyze_satd[handle_analyze_satd]
    src_services_defect_probability_interpolate_cdf[interpolate_cdf]
    src_models_mod[mod]
    src_unified_protocol_adapters_http_process_http_request[process_http_request]
    src_demo_mod_protocol_to_string[protocol_to_string]
    src_demo_mod_runner[runner]
    src_tests_template_rendering[template_rendering]
    src_tests_mcp_protocol_test_handle_call_tool_invalid_tool[test_handle_call_tool_invalid_tool]
    src_tests_tools_test_handle_tool_call_invalid_params[test_handle_tool_call_invalid_params]
    src_tests_mcp_protocol_test_protocol_version_default[test_protocol_version_default]
    src_tests_models_test_template_category_serialization[test_template_category_serialization]
    src_tests_template_resources_test_template_toolchains[test_template_toolchains]
    src_tests_tools_test_validate_template_missing_required[test_validate_template_missing_required]
    src_tests_tools_test_validate_template_valid[test_validate_template_valid]
    src_services_file_discovery_tests[tests]


%% Graph Statistics:
%% Nodes: 1498
%% Edges: 36
