[build]
# Use all available cores
jobs = 16

[target.x86_64-unknown-linux-gnu]
# Use lld linker for faster linking
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.release]
# Optimize for build speed while keeping good runtime performance
opt-level = 2
lto = "thin"
codegen-units = 16
