[build]
# Allow cargo to use optimal parallelism (remove the job limit)
# jobs = 2  # Commented out to use default parallelism

[profile.test]
# Optimize for speed during test compilation
opt-level = 0
codegen-units = 256  # Maximize parallelism
incremental = true   # Enable incremental compilation for faster rebuilds

[env]
# Remove test parallelism limit to use all cores
# RUST_TEST_THREADS = "2"  # Commented out to use default parallelism

# This profile is used by `cargo nextest run --profile fast`
[profile.fast]
inherits = "dev"
opt-level = 0
debug = 0
strip = "none"
lto = "off"
codegen-units = 256
incremental = true