// Agent contract-first enforcement checks (CB-1400 through CB-1410)
// Included from check.rs — do NOT add `use` imports or `#!` attributes here.
//
// Spec: docs/specifications/components/agent-integration.md (Component 10)
//
// Enforces provable-contract-first design for all agents/sub-agents.
// No agent may generate code without a prior contract (YAML or contract.json).

/// Required patterns in agent context files (CLAUDE.md, GEMINI.md, AGENTS.md)
/// that indicate contract-first methodology is documented.
const AGENT_CONTRACT_PATTERNS: &[&str] = &[
    "contract-first",
    "provable-contract",
    "NEVER write code before",
    "NEVER.*code.*before.*contract",
    "CB-1400",
    "verification_level",
    "pmat comply",
];

/// Known AI agent co-author patterns in git commits
const AI_COAUTHOR_PATTERNS: &[&str] = &[
    "Co-Authored-By: Claude",
    "Co-Authored-By: Copilot",
    "Co-Authored-By: GPT",
    "Co-Authored-By: Gemini",
    "Co-Authored-By: Cursor",
    "Co-Authored-By: Cody",
    "Co-Authored-By: Devin",
    "Co-Authored-By: Codex",
    "generated by ai",
    "ai-generated",
];

/// CB-1400: Agent Contract Existence
///
/// Checks that agent context files (CLAUDE.md, GEMINI.md, AGENTS.md) reference
/// contract-first methodology. If agent context files exist but lack contract-first
/// patterns, the project is not enforcing contract-first for agents.
pub(crate) fn check_agent_contract_existence(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let agent_files = [
        "CLAUDE.md",
        "GEMINI.md",
        "AGENTS.md",
        "AGENT.md",
        ".claude/CLAUDE.md",
    ];

    let mut found_agent_files = Vec::new();
    let mut files_with_contract_ref = Vec::new();
    let mut files_missing_contract_ref = Vec::new();

    for agent_file in &agent_files {
        let path = project_path.join(agent_file);
        if path.exists() {
            found_agent_files.push(*agent_file);
            if let Ok(content) = fs::read_to_string(&path) {
                let content_lower = content.to_lowercase();
                let has_contract_ref = AGENT_CONTRACT_PATTERNS
                    .iter()
                    .any(|p| content_lower.contains(&p.to_lowercase()));
                if has_contract_ref {
                    files_with_contract_ref.push(*agent_file);
                } else {
                    files_missing_contract_ref.push(*agent_file);
                }
            }
        }
    }

    if found_agent_files.is_empty() {
        return ComplianceCheck {
            name: "CB-1400: Agent Contract Existence".into(),
            status: CheckStatus::Skip,
            message: "No agent context files found (CLAUDE.md, AGENTS.md, etc.)".into(),
            severity: Severity::Info,
        };
    }

    if files_missing_contract_ref.is_empty() {
        ComplianceCheck {
            name: "CB-1400: Agent Contract Existence".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{}/{} agent context file(s) reference contract-first design",
                files_with_contract_ref.len(),
                found_agent_files.len()
            ),
            severity: Severity::Info,
        }
    } else {
        ComplianceCheck {
            name: "CB-1400: Agent Contract Existence".into(),
            status: CheckStatus::Fail,
            message: format!(
                "{} agent context file(s) lack contract-first reference: {}",
                files_missing_contract_ref.len(),
                files_missing_contract_ref.join(", ")
            ),
            severity: Severity::Error,
        }
    }
}

/// CB-1401: Agent Contract Falsifiability
///
/// Checks that work contracts in .pmat-work/ have falsifiable claims with
/// actual evidence commands (not just descriptions). Contracts with empty
/// evidence fields or placeholder-only claims are flagged.
pub(crate) fn check_agent_contract_falsifiability(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1401: Agent Contract Falsifiability".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut contracts_with_evidence = 0usize;
    let mut contracts_without_evidence = Vec::new();

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            if let Ok(content) = fs::read_to_string(&contract_path) {
                // Check for evidence fields in the contract
                let has_evidence = content.contains("\"evidence\":")
                    && !content.contains("\"evidence\": \"\"")
                    && !content.contains("\"evidence\":\"\"");

                // Check for require/ensure/invariant clauses (DbC v5.0)
                let has_dbc = content.contains("\"require\":")
                    || content.contains("\"ensure\":")
                    || content.contains("\"invariant\":");

                // Check for falsifiable claims (v4 "claims" or v5 "falsifiable_claims")
                let has_claims = content.contains("\"claims\":")
                    || content.contains("\"falsifiable_claims\":");

                if (has_evidence && has_dbc) || has_claims {
                    contracts_with_evidence += 1;
                } else {
                    let id = entry
                        .file_name()
                        .to_string_lossy()
                        .to_string();
                    if contracts_without_evidence.len() < 5 {
                        contracts_without_evidence.push(id);
                    }
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1401: Agent Contract Falsifiability".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found in .pmat-work/".into(),
            severity: Severity::Info,
        };
    }

    if contracts_without_evidence.is_empty() {
        ComplianceCheck {
            name: "CB-1401: Agent Contract Falsifiability".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{}/{} work contract(s) have falsifiable claims with evidence",
                contracts_with_evidence, total_contracts
            ),
            severity: Severity::Info,
        }
    } else {
        ComplianceCheck {
            name: "CB-1401: Agent Contract Falsifiability".into(),
            status: CheckStatus::Fail,
            message: format!(
                "{} contract(s) lack falsifiable evidence: {}",
                contracts_without_evidence.len(),
                contracts_without_evidence.join(", ")
            ),
            severity: Severity::Error,
        }
    }
}

/// CB-1402: Agent Verification Level Floor
///
/// Checks that work contracts specify a verification level >= L1 for
/// autonomous agents. L0 (paper-only/human review) is not acceptable
/// for autonomous agent work.
pub(crate) fn check_agent_verification_level(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1402: Agent Verification Level".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut l0_contracts = Vec::new();
    let mut no_level_contracts = Vec::new();

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            if let Ok(content) = fs::read_to_string(&contract_path) {
                let id = entry.file_name().to_string_lossy().to_string();

                if content.contains("\"verification_level\"") {
                    // Check for L0 — paper-only, unacceptable for autonomous agents
                    if (content.contains("\"L0\"") || content.contains("\"l0\""))
                        && l0_contracts.len() < 5
                    {
                        l0_contracts.push(id);
                    }
                    // L1+ is acceptable
                } else {
                    // No verification level specified — pre-v5.0 contract
                    if no_level_contracts.len() < 5 {
                        no_level_contracts.push(id);
                    }
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1402: Agent Verification Level".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    if !l0_contracts.is_empty() {
        ComplianceCheck {
            name: "CB-1402: Agent Verification Level".into(),
            status: CheckStatus::Fail,
            message: format!(
                "{} contract(s) at L0 (paper-only) — autonomous agents require >= L1: {}",
                l0_contracts.len(),
                l0_contracts.join(", ")
            ),
            severity: Severity::Error,
        }
    } else if !no_level_contracts.is_empty() {
        ComplianceCheck {
            name: "CB-1402: Agent Verification Level".into(),
            status: CheckStatus::Warn,
            message: format!(
                "{} contract(s) missing verification_level field: {}",
                no_level_contracts.len(),
                no_level_contracts.join(", ")
            ),
            severity: Severity::Warning,
        }
    } else {
        ComplianceCheck {
            name: "CB-1402: Agent Verification Level".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{} work contract(s) at verification level >= L1",
                total_contracts
            ),
            severity: Severity::Info,
        }
    }
}

/// CB-1403: Assume-Guarantee Chain Validation
///
/// For multi-agent workflows, validates that work contract ensure clauses
/// from one phase align with require clauses of the next phase.
/// Currently checks that contracts with "parent" or "depends_on" references
/// have matching clause structure.
pub(crate) fn check_assume_guarantee_chain(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1403: Assume-Guarantee Chain".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    // Collect contracts that reference other work items (chain indicators)
    let mut chained_contracts = 0usize;
    let mut total_contracts = 0usize;

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            if let Ok(content) = fs::read_to_string(&contract_path) {
                // Look for chain indicators: iteration > 1, parent references, or
                // require clauses that reference other ticket IDs
                let has_chain_ref = content.contains("\"iteration\":")
                    && !content.contains("\"iteration\": 1")
                    && !content.contains("\"iteration\":1");
                let has_parent = content.contains("\"parent_agent\"")
                    || content.contains("\"depends_on\"");
                let has_refs_pattern = content.contains("Refs PMAT-")
                    || content.contains("refs PMAT-");

                if has_chain_ref || has_parent || has_refs_pattern {
                    chained_contracts += 1;
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1403: Assume-Guarantee Chain".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    // Info-level: report chain status. Future: validate clause alignment.
    ComplianceCheck {
        name: "CB-1403: Assume-Guarantee Chain".into(),
        status: CheckStatus::Pass,
        message: format!(
            "{}/{} contract(s) participate in assume-guarantee chains",
            chained_contracts, total_contracts
        ),
        severity: Severity::Info,
    }
}

/// CB-1404: Agent Comply Check Usage
///
/// Checks that work contracts have falsification receipts — evidence that
/// `pmat comply check` or `pmat work checkpoint` was run during the task.
/// Agents that complete without running comply are operating blind.
pub(crate) fn check_agent_comply_usage(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1404: Agent Comply Usage".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut contracts_with_receipts = 0usize;

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            // Check for evidence of comply/checkpoint run:
            // - falsification/ dir with receipts (from pmat work complete)
            // - checkpoints/ dir with checkpoint files (from pmat work checkpoint)
            // - trend/ dir with metrics snapshots
            let has_falsification = entry.path().join("falsification").exists()
                && fs::read_dir(entry.path().join("falsification"))
                    .map(|d| d.count() > 0)
                    .unwrap_or(false);
            let has_checkpoints = entry.path().join("checkpoints").exists()
                && fs::read_dir(entry.path().join("checkpoints"))
                    .map(|d| d.count() > 0)
                    .unwrap_or(false);

            if has_falsification || has_checkpoints {
                contracts_with_receipts += 1;
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1404: Agent Comply Usage".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    let ratio = contracts_with_receipts as f64 / total_contracts as f64;
    if ratio >= 0.8 {
        ComplianceCheck {
            name: "CB-1404: Agent Comply Usage".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{}/{} contract(s) have falsification receipts (comply was run)",
                contracts_with_receipts, total_contracts
            ),
            severity: Severity::Info,
        }
    } else {
        ComplianceCheck {
            name: "CB-1404: Agent Comply Usage".into(),
            status: CheckStatus::Warn,
            message: format!(
                "Only {}/{} contract(s) have receipts — agents should run pmat comply before completing",
                contracts_with_receipts, total_contracts
            ),
            severity: Severity::Warning,
        }
    }
}

/// CB-1405: Contract References Present
///
/// Checks that work contracts have research references (arXiv, spec sections,
/// or oracle links). Contracts without references lack traceability.
pub(crate) fn check_agent_references_present(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1405: Contract References".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut contracts_with_refs = 0usize;

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            if let Ok(content) = fs::read_to_string(&contract_path) {
                let has_refs = content.contains("\"arxiv\"")
                    || content.contains("\"spec_sections\"")
                    || content.contains("\"five_whys_id\"")
                    || content.contains("\"references\"");
                if has_refs {
                    contracts_with_refs += 1;
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1405: Contract References".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    ComplianceCheck {
        name: "CB-1405: Contract References".into(),
        status: CheckStatus::Pass,
        message: format!(
            "{}/{} contract(s) have references (arXiv, spec, five-whys)",
            contracts_with_refs, total_contracts
        ),
        severity: Severity::Info,
    }
}

/// CB-1406: Chain-of-Thought Audit Trail
///
/// Checks that work contracts have chain-of-thought entries. The audit trail
/// documents decision history for future inspection.
pub(crate) fn check_agent_chain_of_thought(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1406: Chain-of-Thought Audit".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut contracts_with_cot = 0usize;

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            if let Ok(content) = fs::read_to_string(&contract_path) {
                // chain_of_thought field with at least one entry
                let has_cot = content.contains("\"chain_of_thought\"")
                    && !content.contains("\"chain_of_thought\": []")
                    && !content.contains("\"chain_of_thought\":[]");
                if has_cot {
                    contracts_with_cot += 1;
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1406: Chain-of-Thought Audit".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    ComplianceCheck {
        name: "CB-1406: Chain-of-Thought Audit".into(),
        status: CheckStatus::Pass,
        message: format!(
            "{}/{} contract(s) have chain-of-thought audit trail",
            contracts_with_cot, total_contracts
        ),
        severity: Severity::Info,
    }
}

/// CB-1407: Five Whys Linked for Defects
///
/// For work contracts related to defects (status=blocked, or tagged as bug/fix),
/// checks that a five_whys_id reference exists in the contract references.
pub(crate) fn check_agent_five_whys_linked(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1407: Five Whys Linked".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut defect_contracts = 0usize;
    let mut defects_with_whys = 0usize;

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }

            if let Ok(content) = fs::read_to_string(&contract_path) {
                // Detect defect-related contracts
                let is_defect = content.contains("\"bug\"")
                    || content.contains("\"fix\"")
                    || content.contains("\"defect\"")
                    || content.contains("\"blocked\"");

                if is_defect {
                    defect_contracts += 1;
                    if content.contains("\"five_whys_id\"") {
                        defects_with_whys += 1;
                    }
                }
            }
        }
    }

    if defect_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1407: Five Whys Linked".into(),
            status: CheckStatus::Pass,
            message: "No defect-related contracts found (check N/A)".into(),
            severity: Severity::Info,
        };
    }

    if defects_with_whys == defect_contracts {
        ComplianceCheck {
            name: "CB-1407: Five Whys Linked".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{}/{} defect contract(s) have five_whys_id reference",
                defects_with_whys, defect_contracts
            ),
            severity: Severity::Info,
        }
    } else {
        ComplianceCheck {
            name: "CB-1407: Five Whys Linked".into(),
            status: CheckStatus::Warn,
            message: format!(
                "{}/{} defect contract(s) lack five_whys_id — use pmat five-whys for root cause",
                defect_contracts - defects_with_whys, defect_contracts
            ),
            severity: Severity::Warning,
        }
    }
}

/// CB-1408: Agent Evidence Executability
///
/// Checks that work contracts have valid evidence mechanisms — either
/// "evidence": "command" strings (DbC v5.0 spec format) or
/// "falsification_method": "MethodName" (Popperian claims format).
/// Contracts with placeholder-only evidence are flagged.
pub(crate) fn check_agent_evidence_executable(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1408: Agent Evidence Executable".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut contracts_with_evidence = 0usize;
    let mut contracts_without_evidence = Vec::new();

    // Known valid falsification methods (Popperian claims format)
    let valid_methods = [
        "ManifestIntegrity", "MetaFalsification", "CoverageGaming",
        "DifferentialCoverage", "AbsoluteCoverage", "TdgRegression",
        "ComplexityRegression", "FileSizeRegression", "SpecQuality",
        "GitHubSync", "SupplyChainIntegrity", "SatdRegression",
        "DeadCodeRegression", "UnwrapRegression",
    ];

    // Known placeholder patterns
    let placeholder_patterns = ["TODO", "FIXME", "placeholder", "TBD"];

    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            if let Ok(content) = fs::read_to_string(&contract_path) {
                let id = entry.file_name().to_string_lossy().to_string();

                // Check for Popperian falsification methods (named variants)
                let has_methods = valid_methods
                    .iter()
                    .any(|m| content.contains(m));

                // Check for falsification_method fields (v5.0 arbitrary commands/strings)
                let has_falsification_method = content.contains("\"falsification_method\":")
                    && !content.contains("\"falsification_method\": \"\"");

                // Check for evidence command strings
                let has_evidence_cmds = content.contains("\"evidence\":")
                    && !content.contains("\"evidence\": \"\"");

                // Any of these counts as executable evidence
                let has_methods = has_methods || has_falsification_method;

                // Check for placeholder-dominated evidence
                let is_placeholder = has_evidence_cmds
                    && !has_methods
                    && content
                        .lines()
                        .filter(|l| l.contains("\"evidence\""))
                        .all(|l| placeholder_patterns.iter().any(|pp| l.contains(pp)));

                if (has_methods || has_evidence_cmds) && !is_placeholder {
                    contracts_with_evidence += 1;
                } else if contracts_without_evidence.len() < 5 {
                    contracts_without_evidence.push(id);
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1408: Agent Evidence Executable".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    if contracts_without_evidence.is_empty() {
        ComplianceCheck {
            name: "CB-1408: Agent Evidence Executable".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{}/{} contract(s) have valid evidence mechanisms (falsification methods or commands)",
                contracts_with_evidence, total_contracts
            ),
            severity: Severity::Info,
        }
    } else {
        ComplianceCheck {
            name: "CB-1408: Agent Evidence Executable".into(),
            status: CheckStatus::Fail,
            message: format!(
                "{} contract(s) lack valid evidence: {}",
                contracts_without_evidence.len(),
                contracts_without_evidence.join(", ")
            ),
            severity: Severity::Error,
        }
    }
}

/// CB-1409: No L0 Autonomous Code
///
/// Checks recent git commits for AI co-author markers. If found, verifies
/// that a corresponding work contract exists in .pmat-work/. AI-authored
/// commits without contracts indicate L0 (paper-only) autonomous code.
pub(crate) fn check_no_l0_autonomous_code(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    // Get recent commits (last 20)
    let output = match std::process::Command::new("git")
        .args(["log", "--format=%H %s%n%b", "-20"])
        .current_dir(project_path)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .output()
    {
        Ok(o) => o,
        Err(_) => {
            return ComplianceCheck {
                name: "CB-1409: No L0 Autonomous Code".into(),
                status: CheckStatus::Skip,
                message: "Unable to read git log".into(),
                severity: Severity::Info,
            };
        }
    };

    let log_output = String::from_utf8_lossy(&output.stdout);
    if log_output.is_empty() {
        return ComplianceCheck {
            name: "CB-1409: No L0 Autonomous Code".into(),
            status: CheckStatus::Skip,
            message: "No git history found".into(),
            severity: Severity::Info,
        };
    }

    let mut ai_commits = 0usize;
    let mut ai_commits_with_contract = 0usize;
    let mut ai_commits_without_contract = Vec::new();

    // Collect existing work item IDs
    let work_dir = project_path.join(".pmat-work");
    let mut known_work_ids: Vec<String> = Vec::new();
    if work_dir.exists() {
        if let Ok(entries) = fs::read_dir(&work_dir) {
            for entry in entries.flatten() {
                if entry.path().is_dir() {
                    known_work_ids.push(entry.file_name().to_string_lossy().to_string());
                }
            }
        }
    }

    // Parse git log output — format is: <hash> <subject>\n<body>\n
    let mut current_subject = String::new();
    let mut current_body = String::new();
    let mut in_body = false;

    for line in log_output.lines() {
        // New commit starts with a 40-char hex hash
        if line.len() > 41 && line.chars().take(40).all(|c| c.is_ascii_hexdigit()) {
            // Process previous commit if it was AI-authored
            if !current_subject.is_empty() {
                process_commit_for_ai_check(
                    &current_subject,
                    &current_body,
                    &known_work_ids,
                    &mut ai_commits,
                    &mut ai_commits_with_contract,
                    &mut ai_commits_without_contract,
                );
            }
            current_subject = line[41..].to_string();
            current_body.clear();
            in_body = false;
        } else {
            if !in_body {
                in_body = true;
            }
            current_body.push_str(line);
            current_body.push('\n');
        }
    }
    // Process the last commit
    if !current_subject.is_empty() {
        process_commit_for_ai_check(
            &current_subject,
            &current_body,
            &known_work_ids,
            &mut ai_commits,
            &mut ai_commits_with_contract,
            &mut ai_commits_without_contract,
        );
    }

    if ai_commits == 0 {
        return ComplianceCheck {
            name: "CB-1409: No L0 Autonomous Code".into(),
            status: CheckStatus::Pass,
            message: "No AI-authored commits in recent history (last 20 commits)".into(),
            severity: Severity::Info,
        };
    }

    if ai_commits_without_contract.is_empty() {
        ComplianceCheck {
            name: "CB-1409: No L0 Autonomous Code".into(),
            status: CheckStatus::Pass,
            message: format!(
                "{}/{} AI-authored commit(s) have corresponding work contracts",
                ai_commits_with_contract, ai_commits
            ),
            severity: Severity::Info,
        }
    } else {
        let examples: Vec<&str> = ai_commits_without_contract
            .iter()
            .take(3)
            .map(|s| s.as_str())
            .collect();
        ComplianceCheck {
            name: "CB-1409: No L0 Autonomous Code".into(),
            status: CheckStatus::Warn,
            message: format!(
                "{}/{} AI-authored commit(s) lack work contracts: {}",
                ai_commits_without_contract.len(),
                ai_commits,
                examples.join("; ")
            ),
            severity: Severity::Warning,
        }
    }
}

/// Helper: check if a commit is AI-authored and has a work contract reference
fn process_commit_for_ai_check(
    subject: &str,
    body: &str,
    known_work_ids: &[String],
    ai_commits: &mut usize,
    ai_commits_with_contract: &mut usize,
    ai_commits_without_contract: &mut Vec<String>,
) {
    let full_text = format!("{}\n{}", subject, body);
    let is_ai = AI_COAUTHOR_PATTERNS
        .iter()
        .any(|p| full_text.to_lowercase().contains(&p.to_lowercase()));

    if !is_ai {
        return;
    }

    *ai_commits += 1;

    // Check if commit references a known work item
    let has_contract_ref = known_work_ids
        .iter()
        .any(|id| full_text.contains(id));

    // Also check for Refs PMAT-xxx pattern
    let has_refs = full_text.contains("Refs PMAT-")
        || full_text.contains("refs PMAT-")
        || full_text.contains("Contract:");

    if has_contract_ref || has_refs {
        *ai_commits_with_contract += 1;
    } else {
        let truncated = if subject.len() > 60 {
            format!("{}...", &subject[..57])
        } else {
            subject.to_string()
        };
        if ai_commits_without_contract.len() < 5 {
            ai_commits_without_contract.push(truncated);
        }
    }
}

/// CB-1410: Sub-Agent Contract Composition
///
/// Validates that iterative work contracts (iteration > 1) properly
/// reference their predecessor's postconditions. Checks that the
/// contract chain is continuous.
pub(crate) fn check_subagent_contract_composition(project_path: &Path) -> ComplianceCheck {
    debug_assert!(project_path.exists(), "project_path must exist: {}", project_path.display());
    let work_dir = project_path.join(".pmat-work");
    if !work_dir.exists() {
        return ComplianceCheck {
            name: "CB-1410: Sub-Agent Composition".into(),
            status: CheckStatus::Skip,
            message: "No .pmat-work/ directory found".into(),
            severity: Severity::Info,
        };
    }

    let mut total_contracts = 0usize;
    let mut iterated_contracts = 0usize;

    // Check for contracts with iteration markers or receipt chains
    if let Ok(entries) = fs::read_dir(&work_dir) {
        for entry in entries.flatten() {
            let contract_path = entry.path().join("contract.json");
            if !contract_path.exists() {
                continue;
            }
            total_contracts += 1;

            // Check for falsification receipts (indicates contract was evaluated)
            let receipt_dir = entry.path().join("falsification");
            if receipt_dir.exists() {
                if let Ok(receipts) = fs::read_dir(&receipt_dir) {
                    let receipt_count = receipts.filter_map(|r| r.ok()).count();
                    if receipt_count > 1 {
                        iterated_contracts += 1;
                    }
                }
            }
        }
    }

    if total_contracts == 0 {
        return ComplianceCheck {
            name: "CB-1410: Sub-Agent Composition".into(),
            status: CheckStatus::Skip,
            message: "No work contracts found".into(),
            severity: Severity::Info,
        };
    }

    ComplianceCheck {
        name: "CB-1410: Sub-Agent Composition".into(),
        status: CheckStatus::Pass,
        message: format!(
            "{}/{} contract(s) have multi-iteration falsification chains",
            iterated_contracts, total_contracts
        ),
        severity: Severity::Info,
    }
}

#[cfg(test)]
mod tests_agent_contracts {
    use super::*;

    // --- CB-1400 tests ---

    #[test]
    fn test_cb1400_skip_no_agent_files() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_contract_existence(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
        assert!(result.message.contains("No agent context files"));
    }

    #[test]
    fn test_cb1400_pass_claude_md_with_contract_ref() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        std::fs::write(
            tmp.path().join("CLAUDE.md"),
            "# Instructions\n\nUse contract-first design.\npmat comply check required.\n",
        )
        .unwrap();
        let result = check_agent_contract_existence(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
        assert!(result.message.contains("1/1"));
    }

    #[test]
    fn test_cb1400_fail_agent_file_without_contract_ref() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        std::fs::write(
            tmp.path().join("CLAUDE.md"),
            "# Instructions\n\nJust write code.\n",
        )
        .unwrap();
        let result = check_agent_contract_existence(tmp.path());
        assert_eq!(result.status, CheckStatus::Fail);
        assert!(result.message.contains("CLAUDE.md"));
    }

    #[test]
    fn test_cb1400_mixed_agent_files() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        std::fs::write(
            tmp.path().join("CLAUDE.md"),
            "# Instructions\nUse contract-first approach.\n",
        )
        .unwrap();
        std::fs::write(
            tmp.path().join("AGENTS.md"),
            "# Agent Protocol\nNo contract references here.\n",
        )
        .unwrap();
        let result = check_agent_contract_existence(tmp.path());
        assert_eq!(result.status, CheckStatus::Fail);
        assert!(result.message.contains("AGENTS.md"));
    }

    // --- CB-1401 tests ---

    #[test]
    fn test_cb1401_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_contract_falsifiability(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1401_pass_contract_with_evidence() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-001");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"require": [{"description": "builds", "evidence": "cargo build"}],
                "ensure": [{"description": "tests pass", "evidence": "cargo test"}],
                "claims": [{"method": "Test"}]}"#,
        )
        .unwrap();
        let result = check_agent_contract_falsifiability(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    #[test]
    fn test_cb1401_fail_contract_without_evidence() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-001");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"title": "Just a title", "status": "planned"}"#,
        )
        .unwrap();
        let result = check_agent_contract_falsifiability(tmp.path());
        assert_eq!(result.status, CheckStatus::Fail);
        assert!(result.message.contains("PMAT-001"));
    }

    // --- CB-1402 tests ---

    #[test]
    fn test_cb1402_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_verification_level(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1402_pass_l3_contract() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-002");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"verification_level": "L3", "require": []}"#,
        )
        .unwrap();
        let result = check_agent_verification_level(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    #[test]
    fn test_cb1402_fail_l0_contract() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-003");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"verification_level": "L0", "require": []}"#,
        )
        .unwrap();
        let result = check_agent_verification_level(tmp.path());
        assert_eq!(result.status, CheckStatus::Fail);
        assert!(result.message.contains("L0"));
    }

    #[test]
    fn test_cb1402_warn_no_level() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-004");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"require": [], "ensure": []}"#,
        )
        .unwrap();
        let result = check_agent_verification_level(tmp.path());
        assert_eq!(result.status, CheckStatus::Warn);
        assert!(result.message.contains("missing verification_level"));
    }

    // --- CB-1403 tests ---

    #[test]
    fn test_cb1403_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_assume_guarantee_chain(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1403_pass_with_refs() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-005");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"title": "Test", "iteration": 2, "require": []}"#,
        )
        .unwrap();
        let result = check_assume_guarantee_chain(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
        assert!(result.message.contains("1/1"));
    }

    // --- CB-1408 tests ---

    #[test]
    fn test_cb1408_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_evidence_executable(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1408_pass_with_falsification_methods() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-006");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"claims": [{"falsification_method": "ManifestIntegrity"},
                           {"falsification_method": "AbsoluteCoverage"}]}"#,
        )
        .unwrap();
        let result = check_agent_evidence_executable(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
        assert!(result.message.contains("1/1"));
    }

    #[test]
    fn test_cb1408_pass_with_evidence_commands() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-006b");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"require": [{"description": "builds", "evidence": "cargo build"}]}"#,
        )
        .unwrap();
        let result = check_agent_evidence_executable(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    #[test]
    fn test_cb1408_fail_no_evidence_or_methods() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-007");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"title": "No evidence at all", "status": "in_progress"}"#,
        )
        .unwrap();
        let result = check_agent_evidence_executable(tmp.path());
        assert_eq!(result.status, CheckStatus::Fail);
        assert!(result.message.contains("lack valid evidence"));
    }

    // --- CB-1409 tests ---

    #[test]
    fn test_cb1409_skip_no_git() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_no_l0_autonomous_code(tmp.path());
        // No git repo → skip or pass (depends on git availability)
        assert!(
            result.status == CheckStatus::Skip || result.status == CheckStatus::Pass,
            "Expected Skip or Pass, got {:?}",
            result.status
        );
    }

    // --- CB-1404 tests ---

    #[test]
    fn test_cb1404_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_comply_usage(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1404_pass_with_receipts() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-010");
        let receipt_dir = work_dir.join("falsification");
        std::fs::create_dir_all(&receipt_dir).unwrap();
        std::fs::write(work_dir.join("contract.json"), r#"{"version": "5.0"}"#).unwrap();
        std::fs::write(receipt_dir.join("receipt-1.json"), "{}").unwrap();
        let result = check_agent_comply_usage(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    #[test]
    fn test_cb1404_pass_with_checkpoints() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-010b");
        let checkpoint_dir = work_dir.join("checkpoints");
        std::fs::create_dir_all(&checkpoint_dir).unwrap();
        std::fs::write(work_dir.join("contract.json"), r#"{"version": "5.0"}"#).unwrap();
        std::fs::write(checkpoint_dir.join("checkpoint-1.json"), "{}").unwrap();
        let result = check_agent_comply_usage(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    #[test]
    fn test_cb1404_warn_no_receipts() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-011");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(work_dir.join("contract.json"), r#"{"version": "5.0"}"#).unwrap();
        let result = check_agent_comply_usage(tmp.path());
        assert_eq!(result.status, CheckStatus::Warn);
    }

    // --- CB-1405 tests ---

    #[test]
    fn test_cb1405_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_references_present(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1405_pass_with_references() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-012");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"references": {"arxiv": "2602.22302", "spec_sections": ["§3"]}}"#,
        )
        .unwrap();
        let result = check_agent_references_present(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
        assert!(result.message.contains("1/1"));
    }

    // --- CB-1406 tests ---

    #[test]
    fn test_cb1406_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_agent_chain_of_thought(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1406_pass_with_cot() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-013");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"chain_of_thought": [{"step": "Analyzed root cause", "timestamp": "2026-04-03"}]}"#,
        )
        .unwrap();
        let result = check_agent_chain_of_thought(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
        assert!(result.message.contains("1/1"));
    }

    // --- CB-1407 tests ---

    #[test]
    fn test_cb1407_pass_no_defects() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-014");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"title": "New feature", "type": "feature"}"#,
        )
        .unwrap();
        let result = check_agent_five_whys_linked(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    #[test]
    fn test_cb1407_warn_defect_without_whys() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-015");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"title": "fix bug", "type": "fix"}"#,
        )
        .unwrap();
        let result = check_agent_five_whys_linked(tmp.path());
        assert_eq!(result.status, CheckStatus::Warn);
    }

    #[test]
    fn test_cb1407_pass_defect_with_whys() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-016");
        std::fs::create_dir_all(&work_dir).unwrap();
        std::fs::write(
            work_dir.join("contract.json"),
            r#"{"title": "fix bug", "type": "fix",
                "references": {"five_whys_id": "5W-2026-001"}}"#,
        )
        .unwrap();
        let result = check_agent_five_whys_linked(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
    }

    // --- CB-1410 tests ---

    #[test]
    fn test_cb1410_skip_no_work_dir() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let result = check_subagent_contract_composition(tmp.path());
        assert_eq!(result.status, CheckStatus::Skip);
    }

    #[test]
    fn test_cb1410_pass_with_receipts() {
        let tmp = tempfile::tempdir().expect("create tempdir");
        let work_dir = tmp.path().join(".pmat-work").join("PMAT-008");
        let receipt_dir = work_dir.join("falsification");
        std::fs::create_dir_all(&receipt_dir).unwrap();
        std::fs::write(work_dir.join("contract.json"), r#"{"version": "5.0"}"#).unwrap();
        std::fs::write(receipt_dir.join("receipt-1.json"), "{}").unwrap();
        std::fs::write(receipt_dir.join("receipt-2.json"), "{}").unwrap();
        let result = check_subagent_contract_composition(tmp.path());
        assert_eq!(result.status, CheckStatus::Pass);
        assert!(result.message.contains("1/1"));
    }
}
