//! The corpus, its exclusions, and G1.

use super::corpus::{
    classify_generated, collect, generated_by_marker, generated_by_name, header, path_exclusion,
    tracked_paths, CorpusError, Exclusion, Generated, R1_PATHSPECS,
};
use std::path::Path;

// ----------------------------------------------------------------- G1 name --

#[test]
fn g1_reads_generated_filename_conventions() {
    for path in [
        "crates/aprender-cgp/src/generated_contracts.rs",
        "src/generated/mod.rs",
        "src/schema.gen.rs",
        "proto/service_pb2.py",
        "tools/autogen_tables.rs",
    ] {
        assert!(generated_by_name(path), "not read as generated: {path}");
    }
    for path in [
        "src/services/numeric_claims/cohort.rs",
        "crates/aprender-cgp/README.md",
        "CLAUDE.md",
        "src/degenerate_cases.rs",
    ] {
        assert!(
            !generated_by_name(path),
            "wrongly read as generated: {path}"
        );
    }
}

// --------------------------------------------------------------- G1 marker --

/// The exact banner every flagship false positive sat behind.
#[test]
fn g1_reads_do_not_edit_markers() {
    for head in [
        "// Auto-generated contract assertions from YAML — DO NOT EDIT.",
        "// @generated by build.rs",
        "<!-- automatically generated, do not edit -->",
        "# AUTOGENERATED FILE",
    ] {
        assert!(generated_by_marker(head), "marker missed: {head:?}");
    }
    for head in [
        "// Contract assertions, hand-written and reviewed.",
        "# Coverage configuration",
        "Part of the Aprender monorepo — 70 workspace crates.",
    ] {
        assert!(!generated_by_marker(head), "false marker: {head:?}");
    }
}

/// A marker that is not in the header is not a banner — otherwise any file
/// discussing generated code disappears from the corpus, including this one's
/// own documentation.
#[test]
fn g1_marker_must_be_in_the_header() {
    let buried = "line 1\nline 2\nline 3\nline 4\nline 5\n// DO NOT EDIT\n";
    assert_eq!(header(buried).lines().count(), 5);
    assert!(!generated_by_marker(&header(buried)));
    assert_eq!(classify_generated("src/a.rs", buried), None);

    let banner = "// DO NOT EDIT\nline 2\n";
    assert_eq!(
        classify_generated("src/a.rs", banner),
        Some(Generated::ByMarker)
    );
}

#[test]
fn g1_prefers_the_filename_verdict() {
    assert_eq!(
        classify_generated("src/generated_tables.rs", "hand written, honest\n"),
        Some(Generated::ByName)
    );
}

// ------------------------------------------------------------- exclusions --

#[test]
fn machine_managed_paths_are_excluded() {
    for path in [
        "Cargo.lock",
        "vendor/foo/README.md",
        "crates/x/vendor/y.toml",
        "target/debug/build.rs",
        "node_modules/pkg/index.md",
        "assets/app.min.js",
    ] {
        assert_eq!(
            path_exclusion(path),
            Some(Exclusion::MachineManaged),
            "{path}"
        );
    }
}

#[test]
fn fixture_and_state_trees_are_excluded() {
    for path in [
        "tests/fixtures/numeric_claims/planted.md",
        "tests/testdata/a.toml",
        "golden/trace.yaml",
        "src/snapshots/x.md",
        "baselines/2026.toml",
        ".pmat/context.idx",
        ".pmat-work/notes.md",
        "dist/index.md",
    ] {
        assert_eq!(path_exclusion(path), Some(Exclusion::FixtureTree), "{path}");
    }
}

/// A changelog is a record of PAST state. Flagging it for not re-measuring
/// deleted code was the single largest false-positive source in the research.
#[test]
fn changelogs_are_excluded() {
    for path in [
        "CHANGELOG.md",
        "docs/CHANGELOG-3.x.md",
        "crates/a/CHANGELOG",
    ] {
        assert_eq!(path_exclusion(path), Some(Exclusion::Changelog), "{path}");
    }
    assert_eq!(path_exclusion("docs/changelog-policy.md"), None);
}

#[test]
fn ordinary_paths_survive() {
    for path in [
        "CLAUDE.md",
        "crates/aprender-cgp/README.md",
        ".pmat-metrics.toml",
        "src/services/numeric_claims/cohort.rs",
        "codecov.yml",
    ] {
        assert_eq!(path_exclusion(path), None, "{path}");
    }
}

/// `*.json` is absent from R1's pathspecs on purpose: pulling aprender's 3,318
/// machine-written `contract.json` files in yields 3.3M numerals and not one
/// human claim.
#[test]
fn r1_pathspecs_exclude_interchange_formats() {
    assert!(!R1_PATHSPECS.contains(&"*.json"));
    for spec in ["*.md", "*.rs", "*.toml", "*.yaml", "*.yml"] {
        assert!(R1_PATHSPECS.contains(&spec), "missing {spec}");
    }
}

// ------------------------------------------------------------------- git --

/// An unreadable corpus must be an ERROR, never an empty list. "There is no
/// repository here" and "this repository has no matching files" print the same
/// empty output, and only one of them is a clean result.
#[test]
fn a_non_git_directory_is_an_error_not_an_empty_corpus() {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("a.md"), "There are 70 crates.\n").expect("write fixture");

    match tracked_paths(dir.path(), R1_PATHSPECS) {
        Err(CorpusError::NotAGitWorkTree(_)) => {}
        other => unreachable!("a non-git directory must not report a corpus: {other:?}"),
    }
    assert!(collect(dir.path(), R1_PATHSPECS).is_err());
}

/// The live corpus over this repository. A census this small would mean the
/// scanner rotted, which is the failure the vacuity guard exists to catch.
#[test]
fn the_corpus_of_this_repository_is_not_empty() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let (files, census) = collect(root, R1_PATHSPECS).expect("pmat is a git work tree");

    assert!(census.tracked > 100, "census: {census:?}");
    assert_eq!(files.len(), census.scanned);
    assert!(census.scanned > 100, "census: {census:?}");
    assert!(
        census.excluded_changelog > 0,
        "this repository has a CHANGELOG: {census:?}"
    );
    assert!(
        !files.iter().any(|f| f.path.starts_with("target/")),
        "build output must never be in the corpus"
    );
}
