#!/usr/bin/env bash
# CRUX-05 — CLI usage/error-context/suggestions audit (spec section 8.5, issue 1148, PMAT-634).
# Nine legs; five labelled CONTROL are green by design and reject the lazy fixes.

set -euo pipefail
fail(){ echo "FAIL: $*"; exit 1; }
# clap exits 2 on a usage error, so `pmat … | grep` under pipefail returns 2 even
# when grep matches. Capture first, match second.
run(){ out=$("$@" 2>&1 || true); }
say(){ printf '%s' "$out"; }

# ---- leg 1 — root usage line -------------------------------------------- GATE
pmat --help | grep -qE '^Usage: +pmat .*<COMMAND>' || fail "leg 1: root Usage line"

# ---- leg 2 — second-level usage line ------------------------------------ GATE
pmat quality-gate --help | grep -qE '^Usage: +pmat quality-gate' || fail "leg 2"

# ---- leg 3 — DIFFERENTIAL error context --------------------------------- GATE
run pmat analyze complexity -p /tmp/zzsentinel-Q7x --zzz-nope
say | grep -qF -- '--zzz-nope' || fail "leg 3a: error does not name the bad flag"
if say | grep -qF -- 'zzsentinel-Q7x'; then
  fail "leg 3b CONTROL: error echoes argv instead of identifying the token"
fi
say | grep -qF "For more information, try '" || fail "leg 3c: no error-context footer"

# ---- leg 4 — NEAREST-NEIGHBOUR suggestions ------------------------------ GATE
run pmat analyze complexit
say | grep -qw 'complexity' || fail "leg 4a: no suggestion for 'complexit'"
run pmat analyze dead-cod
say | grep -qw 'dead-code'  || fail "leg 4b: no suggestion for 'dead-cod'"
if say | grep -qw 'complexity'; then
  fail "leg 4c CONTROL: suggestion is constant, not computed"
fi
run pmat analyze zzzzqqqq
if say | grep -qwE 'complexity|dead-code'; then
  fail "leg 4d CONTROL: suggests a neighbour for a nonsense token"
fi

# ---- leg 5 — every advertised subcommand, as an INVARIANT ---------------- GATE
cmds=$(pmat --help | awk '/^Commands:/{f=1;next} /^Options:/{f=0} f && /^  [a-z]/ {print $1}' | sort -u)
# anti-shrink guard, stated as an invariant rather than a census pin: the leg must
# not pass by emptying the Commands block.
for spine in analyze context quality-gate query score verify; do
  printf '%s\n' "$cmds" | grep -qx "$spine" \
    || fail "leg 5 guard: '$spine' absent — extractor broken or surface shrunk"
done
missing=$(printf '%s\n' "$cmds" | while read -r c; do
    if [ "$c" != help ]; then          # clap's built-in; legitimately has no help page
      h=$(pmat "$c" --help 2>&1 || true)
      printf '%s\n' "$h" | grep -qE "^Usage: +pmat $c( |\$)" || printf '%s\n' "$c"
    fi
  done)
[ -z "$missing" ] || fail "leg 5: no usable Usage line for: $(printf '%s' "$missing" | tr '\n' ' ')"

# ---- leg 6 — full path AND placeholder on the SAME line ------------------ GATE
u=$(pmat analyze complexity --help | grep -m1 -E '^Usage:' || true)
printf '%s' "$u" | grep -qE '^Usage: +pmat analyze complexity +(\[OPTIONS\]|<|\.\.\.)' \
  || fail "leg 6a: leaf usage line is not the full three-level path + placeholder"
if printf '%s' "$u" | grep -qF '<COMMAND>'; then
  fail "leg 6b CONTROL: leaf command advertises <COMMAND> — one format string, not clap"
fi
pmat analyze --help | grep -qE '^Usage: +pmat analyze .*<COMMAND>' \
  || fail "leg 6c: parent usage line omits <COMMAND>"

# ---- leg 7 — the mechanism ----------------------------------------------- GATE
[ "$(grep -c '^clap = ' Cargo.toml)" -eq 1 ] || fail "leg 7a: not exactly one clap dependency line"
line=$(grep -m1 '^clap = ' Cargo.toml)
for f in usage error-context suggestions; do
  printf '%s' "$line" | grep -qF "\"$f\"" || fail "leg 7b: Cargo.toml clap lacks \"$f\""
done
if grep -rq --include='*.rs' 'override_usage' src/; then
  fail "leg 7c CONTROL: usage is hardcoded, not generated by clap"
fi

# ---- leg 8 — the blind guards -------------------------------------------- GATE
bare=$(grep -rn 'contains("Usage:")' src/ tests/ | wc -l || true)
[ "$bare" -eq 0 ] || fail "leg 8: $bare bare contains(\"Usage:\") predicates remain"

# ---- leg 9 — the shipped artefact, not just the manifest ----------------- GATE
bin=$(command -v pmat) || fail "leg 9: pmat not on PATH"
grep -qaE ' (a|some) similar ' "$bin" \
  || fail "leg 9: clap's did_you_mean literals absent from the binary"

echo "ALL LEGS PASS"
