graph TD
    utils[utils]
    handlers[handlers]
    cli[cli]
    services[services]
    models[models]
    lib[lib]

    lib --- handlers
    handlers --- services
    services --- models
    cli --- services
    services --- utils
