name: Dependencies

on:
  schedule:
    # Run at 8 AM UTC every Monday
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-rust-dependencies:
    name: Update Rust Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Update dependencies
        run: |
          cd server
          cargo update
      
      - name: Test updated dependencies
        run: |
          cd server
          cargo test --all-features
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Rust dependencies"
          title: "chore: update Rust dependencies"
          body: |
            ## Automated Dependency Update
            
            This PR updates the Rust dependencies to their latest versions.
            
            ### What's Changed
            - Updated `Cargo.lock` with latest dependency versions
            
            ### Checklist
            - [ ] All tests pass
            - [ ] No breaking changes identified
            - [ ] Application builds successfully
          branch: update-rust-dependencies
          delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run security audit
        run: |
          cd server
          cargo audit
      
      - name: Create issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Security vulnerabilities found in dependencies';
            const body = `Security audit has found vulnerabilities in the project dependencies.
            
            Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.
            
            Run \`cargo audit\` locally to see the full report.`;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'dependencies']
            });